### ISSUE TITLE
project.docker is not resolving correctly with dnsmasq.

### ISSUE THREAD

**Issue by idyll** [codekitchen/dinghy#10]
I think you need the following change to dnsmasq.plist (add a `.` in front of docker)
```
<string>--address=/.docker/192.168.42.10</string>
```

**Comment by codekitchen** [comment]
Hey @idyll , can you describe the issue you're seeing with the current version? I know of quite a few people using it successfully, and I can't find anything in the dnsmasq documentation that would indicate needing to add a dot.

**Comment by idyll** [comment]
I can't resolver app_name.docker without it.

**Comment by codekitchen** [comment]
hm, I'm not sure why you would be the first one to encounter such an issue. Maybe you have an older version of dnsmasq? I tried making the change and haven't been able to find any issues with it though, so I'm OK with it if it fixes a problem.

It's on master now, and will go out with the next release. Thanks for the report.
