### ISSUE TITLE
Support regenerate-certs command from docker-machine

### ISSUE THREAD

**Issue by michaellopez** [codekitchen/dinghy#109]
Having a docker-machine VM running messes up dinghy. DHCP will give a new IP to dinghy and the certs are only valid for 192.168.99.100. So `docker-machine regenerate-certs <machine name>` is what you run to work around it in docker-machine. Can the same thing be supported in dinghy?

**Comment by michaellopez** [comment]
Since dingy is on top of docker-machine I could issue `docker-machine regenerate-certs dinghy` and `dinghy restart` and I was back. Maybe document this?

**Comment by codekitchen** [comment]
I had that happen once just restarting the dinghy VM too, without any other VM in docker-machine. I think the real fix needs to come from docker-machine (maybe just regenerate automatically when necessary on VM start?) but adding it to the docs for now seems like a good plan.

**Comment by codekitchen** [comment]
This has been merged in and released, thanks again

**Comment by codekitchen** [comment]
Whoops correction, merged but not released to `latest` quite yet, my bad

**Comment by kevinsimper** [comment]
It does not seem that command exist?

**Comment by michaellopez** [comment]
@kevinsimper Which command do you mean?

**Comment by kevinsimper** [comment]
@michaellopez I just thought that dinghy would have all commands that docker-machine had, but I see it now!
