### ISSUE TITLE
Poor performance on VMWare Fusion 8 Pro

### ISSUE THREAD

**Issue by jgeiger** [codekitchen/dinghy#110]
I've been using dinghy for a while on Virtualbox with good results. Last night I tried to convert to using a trial of VMWare Fusion 8 pro.

I was able to get everything set up easily, but when I tried to run my app (Rails) it was unusably slow. I couldn't load my initial login page. While using Virtualbox, everything was nice and snappy.

Is there some special configuration that needs to be set for VMWare to allow the same performance?

The "bug" here is that maybe there's some missing documentation on getting VMWare to work properly?

Also, the reason I'm looking to switch is for the improved networking since I deal with a number of outside devices that need to connect to my running containers.

Thanks.

**Comment by chrisgeo** [comment]
This is unlikely to be related to dinghy, possibly related to [fsevents_to_vm](https://github.com/codekitchen/fsevents_to_vm) which is a wrapper around fsevents written in ruby.

I personally use VMWare Fusion 8 Pro and have noticed nothing but better performance if anecdotal evidence helps.

**Comment by jgeiger** [comment]
The main issue I have is that when I load my initial page, it essentially fails to load. The same issue happens when using VMWare by itself, Virtualbox by itself, with [dlite](https://github.com/nlf/dlite).

The only working case for me at the moment is Virtualbox with dinghy. I was just hoping the Virtualbox -> VMWare swap would be a drop in replacement for dinghy.

**Comment by codekitchen** [comment]
We have a lot of people here at my company using Dinghy with Fusion 8 without issue, so you've probably hit a bug of some sort, maybe something triggered by switching providers. I need to build a new release based on master soon -- in the meantime, you could try a `dinghy destroy` and then follow the instructions to upgrade to master and see if that fixes it. There's been a lot of improvements to how the daemons are managed.

**Comment by jgeiger** [comment]
I think this is an issue with the networking setup for VMWare. Based on the default setup, my attempts to hit my webapp are just slow. It's an nginx container listening on 443 with SSL enabled proxying to a rails app container listening on 3000. It seems there are issues with the default network setup on vmware...

Thanks.

**Comment by codekitchen** [comment]
Well, as I said we have a lot of people using Fusion 8 without seeing that sort of slowness, so there might still be a bug here somewhere. Let me know if you find anything more.
