### ISSUE TITLE
add custom machine size to readme

### ISSUE THREAD

**Issue by markoshust** [codekitchen/dinghy#113]
I needed more space for my virtual machines, as the default (1GB?) filled up very quickly. It would be nice to add this to the README to get more space, increases it to 8GB:

```
docker-machine rm dinghy
docker-machine create --driver virtualbox --swarm-host tcp://192.168.99.100:2376 --virtualbox-memory 8096 dinghy
dinghy up
```

**Comment by codekitchen** [comment]
The README already mentions running `dinghy help create` before creating the machine, which displays options to change disk, cpu and memory parameters. Though the default is 20GB, not 1GB, in every instance that I've seen, I'm not sure how you ended up with a 1GB disk.

**Comment by markoshust** [comment]
Thank you, missed that!
