### ISSUE TITLE
Shared Lib

### ISSUE THREAD

**Issue by digitalhobo** [codekitchen/dinghy#117]
Hi Im trying to access a raw node file on dinghy and seem to get 
"Error: Error loading shared library .... Exec format error at Error (native), is this a docker issue.
Thanks in advance.

**Comment by codekitchen** [comment]
This is not Dinghy related, it sounds like it's trying to load a native extension that wasn't compiled for linux (in the container) -- maybe you previously installed the extension on OS X and it's trying to load that binary. If you mean this is a node app, try just removing `node_modules` and run `npm install` again.

**Comment by digitalhobo** [comment]
Thanks for getting back to me, Yes your right. npm install again worked a charm. Thank You :0)
