### ISSUE TITLE
Parallels support?

### ISSUE THREAD

**Issue by gottfrois** [codekitchen/dinghy#118]
Thanks for this great tool ! Was guessing what it would take to have a Parallels VM adapter as well? Write performance are great it seems http://www.tekrevue.com/2015-vm-benchmarks-parallels-11-vs-fusion-8/10/

Thanks

**Comment by codekitchen** [comment]
Because Dinghy uses NFS to share files between the host and VM, the native Parallels file share performance doesn't affect things much. That is an interesting benchmark, though.

Unfortunately it doesn't look like docker-machine has a Parallels driver yet https://docs.docker.com/machine/drivers/ so the first step would have to be adding that support to docker-machine.

**Comment by gottfrois** [comment]
Right, thanks for the explanation. I'm using a free trial vmware license to give it a try. It "feels" faster but that might just be a feeling. Could be worth spending couple $ since all i'm interested is host -> vm file transfers

**Comment by jgeiger** [comment]
https://github.com/Parallels/docker-machine-parallels

I used this and honestly was able to have it work without dinghy. The only reason I switched back was because this virtualbox was free.

**Comment by codekitchen** [comment]
Oh nice. I'm assuming you just created the machine manually with something like `docker-machine create -d parallels dinghy` and then ran `dinghy start`?

It'd be cool to add real Parallels support to Dinghy then, it should just mean adding a new case to https://github.com/codekitchen/dinghy/blob/latest/cli/dinghy/machine/create_options.rb

**Comment by jgeiger** [comment]
No, I didn't use dinghy at all. It seems like parallels read/write seemed fast enough for my use case. But then I didn't test it very heavily. I was still trying to get the VMware stuff working.

Mainly my comment is that there is a parallels driver in the wild that does seem to work with docker-machine and is being actively worked on.

**Comment by codekitchen** [comment]
Oh, "without dinghy", I misread that. I wonder if Parallels native file sharing fires filesystem events (inotify) in the VM.

**Comment by gottfrois** [comment]
That's great. Would be nice if we can win speed on file sharing !

**Comment by codekitchen** [comment]
Parallels support was just merged into the master branch, install dinghy prerelease to check it out!

**Comment by gottfrois** [comment]
:+1:
