### ISSUE TITLE
Disable Transparent Huge Pages

### ISSUE THREAD

**Issue by gottfrois** [codekitchen/dinghy#119]
Run `docker run -it redis` and you'll get the following warning message:

```
WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
```

I think it should be disabled in boot2docker but since you use a custom image if I understood correctly. Here is the boot2docker issue link: https://github.com/boot2docker/boot2docker/issues/1083

**Comment by adrianfalleiro** [comment]
Since dinghy runs on top of docker-machine it uses boot2docker on OS X.

I've run into this issue before, but resolved it using the fix suggest in the ticket you linked to by running `docker-machine ssh dinghy` and making the necessary changes.

**Comment by gottfrois** [comment]
Alright, thanks for the tip :)

**Comment by codekitchen** [comment]
Agreed, this should be tracked in docker-machine.

**Comment by gottfrois** [comment]
Unfortunately I am not able to run the fix suggested:

```
docker@dinghy:~$ echo never > /sys/kernel/mm/transparent_hugepage/enabled
-sh: can't create /sys/kernel/mm/transparent_hugepage/enabled: Permission denied
docker@dinghy:~$ sudo echo never > /sys/kernel/mm/transparent_hugepage/enabled
-sh: can't create /sys/kernel/mm/transparent_hugepage/enabled: Permission denied
```

**Comment by codekitchen** [comment]
Your `sudo` is only applying to the `echo` command not the write to disk. You could use `tee`, or just run `sudo -i` to get a root shell.

**Comment by gottfrois** [comment]
Thanks man :)
