### ISSUE TITLE
NFS squash root access to local user

### ISSUE THREAD

**Issue by yenif** [codekitchen/dinghy#12]
Currently unfs is set to not munge UIDs leading to the vm having real root access to the shared filesystem and any created files thus having root UID/GID (particularly annoying around `npm install` or `bundle install` into a subdirectory).

Looks like unfs supports root squashing with anonuid and anongid (http://linux.die.net/man/8/unfsd) which we could set to the executing user for this export. Personally I'd go as far to turn on all_squash to also avoid any other UID pollution from the vm, but that could potentially interfere with some future use case (create as non root with only uid read, next read would probably fail with a wrong uid).

Looks like this should be a pretty easy change, will try to throw something up this afternoon.

**Comment by codekitchen** [comment]
Yes this is intentional, to match how the docker daemon works with permission when working on linux directly. I experimented heavily with root squashing, and with all_squash, but various docker images run into issues if they can't create files with user ids and group ids that don't exist on the host system.

**Comment by yenif** [comment]
Ah, well that's annoying...

**Comment by codekitchen** [comment]
I'm going to close this for now -- agree that it's annoying, I hate having all those files on the host OS X filesystem owned by root and other non-existent users, but don't have a better solution for now. I know that docker is looking to add user mapping support, I bet the situation will improve once that's released and image creators start adopting it.
