### ISSUE TITLE
Update nginx-proxy/docker-gen

### ISSUE THREAD

**Issue by michaellopez** [codekitchen/dinghy#120]
With Docker 1.9 new networking model the nginx proxy breaks. [docker-gen](https://github.com/jwilder/docker-gen) has fixed this in [0.5.0](https://github.com/jwilder/docker-gen/releases/tag/0.5.0). I expect [nginx-proxy](https://github.com/jwilder/nginx-proxy/pull/328) to be updated shortly. There is [a PR for updating](https://github.com/jwilder/nginx-proxy/pull/328). When that gets merged you should update dinghy to use that instead so that we can use Docker's new network model.

**Comment by codekitchen** [comment]
Thanks for the report. Can you provide repro steps showing the broken behavior? It'll help with testing the update.

**Comment by codekitchen** [comment]
There is support for the new networking model on dinghy HEAD, see the discussion here: https://github.com/codekitchen/dinghy/issues/135#issuecomment-187389093
