### ISSUE TITLE
Pass virtualbox-host-dns-resolver to dinghy docker-machine

### ISSUE THREAD

**Issue by chrisgeo** [codekitchen/dinghy#123]
This would be a nice to have since it will allow the virtualbox image to use the host dns on the image.

**Comment by codekitchen** [comment]
Dinghy already enables host dns resolving, see https://github.com/codekitchen/dinghy/commit/4cf64e0d786805488a7b88ae1d1960aa1f57b044 , however we do it by directly calling `VBoxManage`, only because that docker-machine option didn't exist at the time.

Are you seeing an issue with this not working?

**Comment by codekitchen** [comment]
Hey @chrisgeo I'm going to close this since there isn't anything actionable here. Go ahead and re-open with more information if you'd like.
