### ISSUE TITLE
How to mount docker volume so it works for different users?

### ISSUE THREAD

**Issue by dcosson** [codekitchen/dinghy#125]
It looks like dinghy just mounts /Users from OSX to /Users in the VM.

In my project's docker-compose file, I'm mounting the code directory as a volume into docker. 

What's the best practice for doing this so it works for all the developers on the team? Obviously different people have different home directory names, plus people might nest the repository at a different place in their home directory.

**Comment by codekitchen** [comment]
This isn't Dinghy specific. docker-machine does the same thing, just not over NFS. The easiest solution is to specify the mounted volumes using relative paths on the host, which docker-compose supports.

**Comment by dcosson** [comment]
Ok, thanks
