### ISSUE TITLE
Virtual hosts not working while offline

### ISSUE THREAD

**Issue by alkiskal** [codekitchen/dinghy#127]
I'm dinghy to build 6 containers. 2 with custom Dockerfiles, containing my applications and 4 dependency systems (e.g. rabbitmq). While I'm connected to the wifi everything works great. Rabbitmq is accessible by the host (management plugin via browser of host). If I turn of the wifi, this doesn't work anymore. 
I can no longer use the VIRTUAL_HOST I've specified in the docker-compose.yml to access the plugin. The containers are bound to 0.0.0.0 so it is accessible via my IP address. As I understand the DNS component no longer maps the virtual hosts I've specified. Can I do something to make it work while offline?

Thank you for your help and for this awesome project. Have fun

**Comment by codekitchen** [comment]
Are you up to date? This was fixed recently https://github.com/codekitchen/dinghy/commit/e6aa7d9d0c7c5ec93a9f15c37dac3eb772aca189

**Comment by alkiskal** [comment]
I have the 4.0.8 version. I will update asap. Sorry for wasting your time.

**Comment by codekitchen** [comment]
No worries. I wish github would let me add a "things to check before filing an issue" message or something.
