### ISSUE TITLE
Support for longer proxy timeout

### ISSUE THREAD

**Issue by marclennox** [codekitchen/dinghy#129]
I'm using dinghy a lot in development, and when running debug breaks, I need the proxy_read_timeout setting in nginx to be much larger than the default 60s, otherwise it times out while debugging.

I've figured out a hack to exec into the proxy container and edit the nginx template, but it would be great to have this as an option.

I see from the nginx-proxy project that it supports custom nginx configuration, is this exposed through dinghy in any way that I can achieve this without the hack?

**Comment by codekitchen** [comment]
There's not a great way for you to do that locally only for your machine right now, though that'd be nice to add. I'm OK with just adding that config to the proxy container if you want to send over a PR: https://github.com/codekitchen/dinghy-http-proxy/blob/master/dinghy.nginx.conf

**Comment by marclennox** [comment]
Thanks, I submitted a PR with the fix, which I've also successfully tested locally.

**Comment by codekitchen** [comment]
Cool thanks @marclennox -- I don't see the PR though, are you sure you sent it over?

**Comment by marclennox** [comment]
Sorry about that, I messed up the PR.  Here it is https://github.com/codekitchen/dinghy-http-proxy/pull/1

**Comment by codekitchen** [comment]
Thanks this is published. You may have to manually run `docker pull codekitchen/dinghy-http-proxy` to get the change.
