### ISSUE TITLE
Access to proxy from LAN (NFS not run)

### ISSUE THREAD

**Issue by dlopezp** [codekitchen/dinghy#133]
I need to access to proxy from LAN, for test in devices.
I try to enable a bridge interface on Virtualbox VM, but NFS don't start:
```
dinghy start
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
NFS mounting failed
Starting the FsEvents daemon
Starting the DNS daemon
Starting the HTTP proxy
An error occurred trying to connect: Post https://192.168.1.64:2376/v1.21/containers/create?name=dinghy_http_proxy: x509: certificate is valid for 192.168.99.101, not 192.168.1.64
  VM: running
 NFS: stopped
FSEV: running
 DNS: running
HTTP: stopped

NFS failed to run
details available in log file: /usr/local/Cellar/dinghy/4.2.0/local/var/dinghy-NFS.output

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.1.64:2376
    export DOCKER_CERT_PATH=/Users/dlopez/.docker/machine/machines/dinghy
    export DOCKER_TLS_VERIFY=1
    export DOCKER_MACHINE_NAME=dinghy
```

The content of dinghy-NFS.output is:
```
UNFS3 unfsd 0.9.22 (C) 2006, Pascal Schmidt <unfs3-server@ewetel.net>
bind: Can't assign requested address
Couldn't bind to udp port 19570
```

**Comment by codekitchen** [comment]
Did you add another network interface, or modify the existing one? Dinghy just asks `docker-machine` for the VM's IP, and this output looks like `docker-machine` returned the wrong interface's IP, so I think you've probably confused it.

As an alternative to changing the virtual network setup, I have quite a few folks at my company using https://github.com/esnunes/my-proxy for the same purpose.

**Comment by dlopezp** [comment]
I add a bridge interface on dinghy VM, and, when this interface is enabled docker-machine return the LAN IP instead of host-only IP.

I wanted to avoid run a proxy in my real host but probably is the most simple solution.

Thx.

**Comment by codekitchen** [comment]
Yeah that might take a change in docker-machine to make it work well, I'd recommend just going the proxy route. I'm going to add something to the FAQ about it, and close this. Thanks.
