### ISSUE TITLE
How do I make custom NFS exports this permanent?

### ISSUE THREAD

**Issue by kourindouhime** [codekitchen/dinghy#134]
Hi, I'm here with an old problem, which you've marked as "won't fix". The problem is related to some of the docker images like postgresql, which can't run with a volume attached, because of unable to change permissions for data files problem.

https://github.com/codekitchen/dinghy/commit/d1cf4d98ffab8852ea7b78fae99114ff6e6aa3ee

^ I took a look on this commit, so I decided to replace exports options in  ~/.dinghy/machine-nfs-exports-dinghy with
    192.168.99.100(rw,no_root_squash)

and restarted nfs manually:

    sudo /usr/local/sbin/unfsd -e /Users/danst/.dinghy/machine-nfs-exports-dinghy -n 19888 -m 19888 -l 192.168.99.1 -p -d

Tried running postgresql container and it was OK. It changed permissions to data folder, I can't access it with my usual user, but I can with root and I'm totally okay with it.

BUT if I do

    dinghy restart

then somewhere on "Starting NFS daemon, this will require sudo" step, my "~/.dinghy/machine-nfs-exports-dinghy" file gets updated with rw,all_squash,anonuid=501,anongid=20.

How can I prevent this happening? Thank you.

**Comment by codekitchen** [comment]
It'll require a code change, I'm open to a PR that makes this a configurable option

**Comment by alexvb** [comment]
@codekitchen A feature called [user namespaces](https://blog.docker.com/2016/02/docker-engine-1-10-security) has landed in the new docker release. Maybe it could be useful to get around all these ownership problems.

**Comment by codekitchen** [comment]
Yep! We've been following the development of user namespaces support for a long time hoping it'll be the true solution. There's still a lot of things to figure out though. Ideally I'd love to see the root user in containers such as postgres mapped to the uid/gid of the OSX host user.

I haven't had a chance to dig in to the finalized feature yet, if you'd like to see what can be done with this first release that'd be awesome.

**Comment by kourindouhime** [comment]
Alright, I've solved this with a horrible workaround:

    75c75
    <     #File.open(exports_filename, 'wb') { |f| f.write exports_body }
    ---
    >     File.open(exports_filename, 'wb') { |f| f.write exports_body }

**Comment by codekitchen** [comment]
A PR for this was merged a while back, I'm going to close this: https://github.com/codekitchen/dinghy/pull/170
