### ISSUE TITLE
`dinghy nfs` is unusable

### ISSUE THREAD

**Issue by fgrehm** [codekitchen/dinghy#138]
Sorry if this has been reported already but I had some NFS issues which made me want to restart the NFS service but unfortunately it didn't work :cry: 

```
$ dinghy version
Dinghy 4.2.0

$ dinghy nfs
ERROR: "dinghy nfs" was called with no arguments
Usage: "dinghy nfs"

$ dinghy nfs start
ERROR: "dinghy nfs" was called with arguments ["start"]
Usage: "dinghy nfs"

$ dinghy nfs stop
ERROR: "dinghy nfs" was called with arguments ["stop"]
Usage: "dinghy nfs"
```

I fixed my problems with a `dinghy restart` but I thought I'd bring this up to your attention :beers:

**Comment by codekitchen** [comment]
Ah dang, thanks for the reminder about this. `dinghy nfs` is an internal-only command that's used since we have to shell out to a new process to `sudo`. I meant to hide it, I'll move it to a separate binary so it doesn't show up in `dinghy help` anymore.
