### ISSUE TITLE
dnsmasq daemon sometimes fails to quit

### ISSUE THREAD

**Issue by codekitchen** [codekitchen/dinghy#140]
A couple times since the switch away from launchd to self-managed daemons, I've seen the dnsmasq daemon continue to run after `stop`/`restart`, causing the new dnsmasq process to fail with `"Address already in use"`.

**Comment by aj-may** [comment]
+1

**Comment by jdchmiel** [comment]
yeah, this.

**Comment by adrianfalleiro** [comment]
Is there any harm in switching back to launchd?

**Comment by codekitchen** [comment]
Yeah the way we were abusing launchd had much worse problems. I haven't tackled this issue yet because I have a co-worker who is pulling the dns/proxy functionality out into a separate project that runs dnsmasq in docker, which will solve this.

**Comment by codekitchen** [comment]
The master branch now runs dnsmasq inside Docker (actually in the http proxy container, see https://github.com/codekitchen/dinghy-http-proxy), so I'm going to close this.
