### ISSUE TITLE
Dinghy should not hide docker-machine errors

### ISSUE THREAD

**Issue by fgrehm** [codekitchen/dinghy#152]
For example, when creating a VM using the xhyve provider and the xhyve driver is not set up, this is what we get on the console:

![image](https://cloud.githubusercontent.com/assets/81859/13537353/506ea09a-e223-11e5-9a81-8b4104a5b59f.png)

According to @zwily, that error did not show up when running `dinghy create`. There are likely other types of errors that can be surfaced to users but this seems like a place to start hunting them down :gun: 

----------

_Fork of https://github.com/codekitchen/dinghy/pull/139#issuecomment-191369738_

**Comment by codekitchen** [comment]
Dinghy already prints out the stderr of the `docker-machine create` command if it fails, so I dug into this a bit more. Turns out it's a bug in the checking logic, so I filed https://github.com/zchee/docker-machine-driver-xhyve/pull/104

Closing this in favor of that fix. Thanks.

**Comment by fgrehm** [comment]
Awesome! Thanks for digging into it!
