### ISSUE TITLE
Containers and file permissions with NFS volumes

### ISSUE THREAD

**Issue by davibe** [codekitchen/dinghy#157]
I am running a container for elastic search. Like many others it does not run as root therefore if i try to share the volume where it writes data it fails at start. The startup error of elastic search tries to chown the data directory which fails on the nfs share.

What's the best solution for this ?

**Comment by davibe** [comment]
i think that vboxfs being ugly and all does have a "feature" that by default ignores the files ownership like an 'umask' and this eliminates such problems

**Comment by davibe** [comment]
I just learned that if I have a shared host volume called /shared

1. when i create a file /shared/test from inside the container as root -> in the host machine that file is chowned to the osx user

2. if i create a file from the osx machine using the normal user /shared/test2 -> the same file inside the container is chowned with an uid the container does not know about (the one of the osx user)

**Comment by codekitchen** [comment]
Dinghy enables "user squashing" on the NFS share which acts much like vboxfs file ownership, but not exactly the same. I'll add something to the FAQ as there has already been a few issues opened and closed on this same topic.

**Comment by codekitchen** [comment]
While I'm doing that, can you expand on (2) in your last comment? Due to user squashing, the docker container can read the file even though it is owned by a uid it doesn't recognize, as long as it is owned by your user on the host OSX machine.

**Comment by davibe** [comment]
ok. Given a `/shared` volume between the container and the OSX host:

A user inside the container can read write and delete a file created by a user of the host.
A user inside the container can also create a new file. This file willl be seen as owned by the user of the host os, not the one in the container. Any chown will fail.

There are a number of services/program/containers trying to chown files in their boot up process, or even just performing checks we can't disable. The examples i ran into in the last 2 days are

- `elasticsearch` docker container checks ownership of the /data folder. If it's not the same as the running user it tries to chown it and it fails. This happens at the entry point level of the docker container therefore ES does not start

- i tried to share `.ssh/` because i wanted to use keys and config inside the container. Again ssh client checks ownership and permissions of `config` and keys and it fails. There is no way to disable this behaviour and there is no way to chown the files (which would be bad anyway)

Even if the behaviour set by dinghy is different compared to what happens on a linux host I think there is a more generic problem with permissions in shared volumes which is being discussed almost everywhere. On linux, files can be chowned by the user inside the container. This makes things messy but also makes it possible to workaround things with a chown and let the containers run.

The correct solution, i think, would be to fake permissions so that every container sees the shared files as its own. Maybe this should be done by Docker itself. Can NFSv3 do this ?

**Comment by codekitchen** [comment]
Yep, it's a common point of discussion both here in Dinghy and in other projects such as boot2docker and docker-machine. I've added a section to [the FAQ](https://github.com/codekitchen/dinghy/blob/master/FAQ.md#im-running-into-file-permissions-issues-on-the-nfs-mounted-volumes), I'm not totally happy with how it's worded yet but it's a start.

I'm not aware of a great solution to your problem with the ssh client wanting different permissions. You could copy the files into the container of course, but I'm assuming you're trying to use a mounted volume because they may change.

For containers like elasticsearch, I'd recommend using a volume in the linux VM and not trying to mount it from the host machine. We do this often with postgres volumes, and it's more performant even than NFS, and it's easy to use docker commands to snapshot and restore the volumes when necessary.

**Comment by davibe** [comment]
I do exactly what you said (copy files and use vm volumes). It just does not feel 100% right. Good to hear i am not alone tho :)

**Comment by codekitchen** [comment]
Yeah, unfortunately that's about the state of the art right now. I'm going to close this issue, but if you find any specific things we can do to improve the situation, definitely open a new issue or PR. Thanks.

**Comment by davibe** [comment]
Let me add this. Even npm can fail on a mounted dinghy volume. 
example
```
backend_1 | npm ERR! tar.unpack untar error /root/.npm/har-validator/2.0.6/package.tgz
backend_1 | npm WARN install:har-validator EPERM: operation not permitted, chown '/data/node_modules/.staging/har-validator-14dc3c0989c220260aeccc15d41b64a6/package.json'
backend_1 | npm ERR! tar.unpack untar error /root/.npm/node-gyp/3.3.1/package.tgz
```
in this case untag or npm are trying to chown files and they are not allowed. At this point i suggest you should add an option to disable nfs squashing and explain it in the docs.

**Comment by subwai** [comment]
@davibe I have the same issue. Were you able to find a work around? Right now my work around is to run npm install in both the Dockerfile and on the host.

**Comment by davibe** [comment]
Unfortunately I have no workaround for this. I have already made my suggestions. I think this issue should be reopened and prioritized.

**Comment by codekitchen** [comment]
`tar` only has that behavior when run as root, running your docker containers as a non-root user will fix it, and is a good idea for lots of other reasons anyway.

**Comment by codekitchen** [comment]
I missed the earlier comments -- I don't really want to add an option to turn off the squashing, as that causes other issues for dinghy's primary use case as a way to mount source code inside containers and edit it directly on the host. I'm open to other suggestions, though.
