### ISSUE TITLE
dinghy up should not restart services

### ISSUE THREAD

**Issue by michaellopez** [codekitchen/dinghy#158]
Hi,

I've been getting this a lot lately. Usually it goes something like this:

```sh
(open new shell)
$ docker build -t some/image .
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
$ dinghy up
dinghy already running, restarting...
Stopping the FsEvents daemon
Stopping the dinghy VM...
Stopping "dinghy"...
Machine "dinghy" was stopped.
Stopping NFS daemon, this will require sudo
Password:
Stopping the DNS daemon
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/<username>
Starting the FsEvents daemon
Starting the DNS daemon
Starting the HTTP proxy
266aabe8d6a6da3957f9c65f8a9b697064154f6dde941265c10bf4a331d15822
  VM: running
 NFS: running
FSEV: running
 DNS: running
HTTP: running

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.99.100:2376
    export DOCKER_CERT_PATH=/Users/<username>/.docker/machine/machines/dinghy
    export DOCKER_TLS_VERIFY=1
    export DOCKER_MACHINE_NAME=dinghy
```
So basically, having missed to set the env vars makes me believe that dinghy services are not running, when in fact they are. Restarting dinghy services takes around 30-60 seconds depending on what's going on at the same time. I also need to type my password or I end up in a state where services are down, which is worse. Total focus killer...just seeing that message `dinghy already running, restarting...` is just irritating. There is a `dinghy restart` for that.

So my humble request is that `dinghy up` only start services, and error out with a nice message explaining that things are running but not restart anything.

**Comment by codekitchen** [comment]
It's your lucky day! This was just changed on master https://github.com/codekitchen/dinghy/issues/153

**Comment by michaellopez** [comment]
@codekitchen Wow, you're awesome. Thanks, love the project, keep up the good work.
