### ISSUE TITLE
How does NFS work?

### ISSUE THREAD

**Issue by mrjackdavis** [codekitchen/dinghy#159]
Hi,

This is probably human error, but I'm trying to figure out how NFS works. The readme doesn't quite explain it enough for me.

My process so far

```
$ brew update
$ brew install dinghy
$ dinghy create
$ dinghy up
$ docker run -i -t ubuntu /bin/bash
$(docker) ls /
> bin  boot  dev	etc  home  lib	lib64  media  mnt  opt	proc  root  run  sbin  srv  sys  tmp  usr  var
```

I expected to see `/Users/me`. But I did not. Please explain where I am going wrong.

**Comment by ryansch** [comment]
You would see it with `dinghy ssh`.  You have to bind mount into the docker container for it to have access: `docker run -it -v /Users/me:/Users/me ubuntu /bin/bash`

**Comment by mrjackdavis** [comment]
Thanks @ryansch.

It was not apparent to me that the usage of NFS was transparent to the container. Perhaps the docs could use a little improvement? I'd be happy to submit a PR

**Comment by codekitchen** [comment]
:+1: documentation improvements are always welcome. thanks!
