### ISSUE TITLE
Add support for docker/machine.

### ISSUE THREAD

**Issue by idyll** [codekitchen/dinghy#16]
The PR for docker/machine to support VMware Fusion network shares has just been accepted into master.

I am going to do some additional testing, but I believe this means the last issues preventing docker/machine from working with VMware. 

Have you considered integration with docker/machine?

**Comment by idyll** [comment]
PR and related issue referenced above:

https://github.com/docker/machine/pull/1034
https://github.com/docker/machine/issues/641#issuecomment-94647735

**Comment by codekitchen** [comment]
Yeah, a couple of us have been talking about running dinghy on top of docker-machine, now that it's starting to stabilize. We wouldn't depend on the vmware network share code, we'd continue to use NFS for improved performance, so that's not a blocker.

I don't have any sort of timeline though, I haven't even fully scoped out what would be involved yet. We do rely on Vagrant to create a private network interface in the VM, so that would be one possible stumbling block.

**Comment by tomdavidson** [comment]
I came across dinghy trying to solve nfs troubles with my rake/docker-machine tool. I like what machine does, different targets, different drivers. VBoxManage can set the network for you if you would like.

**Comment by Oliboy50** [comment]
What about adding your own `dinghy` driver to docker-machine itself?

**Comment by Pixelworlds** [comment]
+1 

"Yeah, a couple of us have been talking about running dinghy on top of docker-machine"

**Comment by codekitchen** [comment]
The work to switch to `docker-machine` has started on a separate branch: https://github.com/codekitchen/dinghy/tree/machine

Everything appears functional, but I'm sure there's still some bugs and rough edges. If anybody wants to start trying it out, I'd love to hear about anything that comes up. You can switch to that branch by running:

    $ brew reinstall --HEAD https://github.com/codekitchen/dinghy/raw/machine/dinghy.rb
    $ dinghy up -p [virtualbox|vmware]

Once the VM is created, it should show up in `docker-machine ls` as normal.

**Comment by codekitchen** [comment]
It doesn't really make sense to make dinghy a docker-machine driver, since it builds on top of the vmwarefusion and virtualbox drivers, it doesn't replace them. Eventually it sounds like machine might have a rich enough plugin system that dinghy can just become a `docker-machine` plugin, but for now it wraps machine, the same way that it wrapped vagrant.

**Comment by chinthakagodawita** [comment]
Been running the machine version of dinghy and it's working beautifully.

The only problem I've had is that it doesn't create a `~/.dinghy` directory on fresh install which means that `dinghy create` fails.

Manually creating that directory and trying `create` again works.

**Comment by codekitchen** [comment]
ah, thanks, that was recently fixed on the master branch. i just cherry-picked the change over to the machine branch.

**Comment by codekitchen** [comment]
This has now been released as dinghy v4.0, see the upgrade instructions in the README

**Comment by mnapoli** [comment]
@codekitchen just to be sure, that means we first install Docker Toolbox, then upgrade Dinghy?

**Comment by codekitchen** [comment]
Hm no, docker-machine is installed via homebrew so Toolbox isn't used. Was there something in the README that made you think it was?

**Comment by mnapoli** [comment]
ah ok, I thought that since Docker toolbox is the new way to install docker, Dinghy would connect to it. I wanted to give a try to Kitematic so Toolbox seemed like a good choice, but I'll pass then.

I'll do the simple upgrade and see how it goes. Thanks a lot for what you do!

**Comment by codekitchen** [comment]
Ah cool. I need to try Toolbox myself, I haven't given it a go yet. It might work just fine with dinghy, but I can't make any promises.

**Comment by mnapoli** [comment]
I went with the brew solution and it works great! Thanks a lot, really that's awesome!

**Comment by smarques** [comment]
What happens if I have docker toolbox already installed and I run the dinghy installer? will it mess my docker machine setup? (really looking forward to try dinghy but I don't want to lose a working setup)
