### ISSUE TITLE
Feature request: dinghy.docker as a virtual host out of the box.

### ISSUE THREAD

**Issue by ryanmt** [codekitchen/dinghy#160]
Would make tools like PSequel or PGAdmin would be trivial to plug in to.

I'm happy to write a PR, just don't have time to chase that down today.

**Comment by codekitchen** [comment]
Can you expand on this a bit? I'm not clear on what you want `dinghy.docker` to point to. Right now `*.docker` points to the boot2docker linux VM.

**Comment by codekitchen** [comment]
I'm going to close this since there hasn't been any activity. Feel free to re-open with more information.
