### ISSUE TITLE
Install issue: To connect the Docker client to the Docker daemon, please set:

### ISSUE THREAD

**Issue by pascalandy** [codekitchen/dinghy#164]
Hi,

I saw his issue
```
To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.99.101:2376
    export DOCKER_CERT_PATH=/Users/pascalandy/.docker/machine/machines/dinghy
    export DOCKER_TLS_VERIFY=1
    export DOCKER_MACHINE_NAME=dinghy
```
I read to FAQ. Ran `docker-machine regenerate-certs dinghy`

but I still have the issue `dinghy status`          

```           
VM: running
NFS: running
FSEV: running
DNS: running
HTTP: stopped

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.99.101:2376
    export DOCKER_CERT_PATH=/Users/pascalandy/.docker/machine/machines/dinghy
    export DOCKER_TLS_VERIFY=1
    export DOCKER_MACHINE_NAME=dinghy
```

It would be great to know how to **set** those values :)

**Comment by adrianfalleiro** [comment]
Try running `eval $(docker-machine env dinghy) in your terminal`

**Comment by pascalandy** [comment]
YES!! 

Via `$(dinghy shellinit)` it worked. Please add this in the FAQ :)

Cheers!

**Comment by codekitchen** [comment]
Hm yeah this does assume some familiarity with shell env vars. We should tweak the "please set" message to make it clear.

**Comment by ryansch** [comment]
Let's just change the help message to something more like `docker-machine env`:

```
Run this command to configure your shell:
eval $(dinghy env)
```

**Comment by codekitchen** [comment]
done on master in https://github.com/codekitchen/dinghy/commit/9032c1c80f7e6df2f0755dd1d8180beec5404cdf

**Comment by ryansch** [comment]
:+1:
