### ISSUE TITLE
DNS nameserver for vm

### ISSUE THREAD

**Issue by shayne** [codekitchen/dinghy#173]
Caveat emptor: I run dnsmasq locally for unrelated-to-docker reasons.

After bringing up dinghy the first docker run I issued failed due to DNS. Sure enough I `dinghy ssh` into the VM and the /etc/resolv.conf has the 192.168.64.X address. It's known to me that there are situations where this doesn't work. My laptop has 127.0.0.1, ::1 as the DNS server going through dnsmasq and I assume that's why.

Updating the nameserver to 8.8.8.8 made everything work, but I would've liked to see a flag or option to provide a DNS server for the vm. I must've missed it if it exists. Any chance there's support for this in preferences.yml?

**Comment by codekitchen** [comment]
You didn't mention what VM provider you are using. For virtualbox we make a change to the default docker-machine settings to [use the host resolver](https://github.com/codekitchen/dinghy/blob/master/cli/dinghy/machine.rb#L162). For others we just use the docker-machine defaults. What you are looking for would likely be a docker-machine addition.

**Comment by shayne** [comment]
@codekitchen using virtualbox. dlite, for example, has a config file to add a DNS server it defaults to 192.168.63.1 (or whatever) and you can change the config and start the vm with the specified DNS server in /etc/resolv.conf.

**Comment by codekitchen** [comment]
Right, since Dinghy just uses docker-machine to actually create and start the VM, it'd make more sense to add such an option there. Or actually, this should be possible by adding a command to the `/var/lib/boot2docker/bootlocal.sh` functionality that boot2docker/docker-machine already has, but I've never tried it myself.

**Comment by codekitchen** [comment]
I'm going to close this since it's an addition that needs to be made in docker-machine. Although if the second option works well, it'd be worth adding that to the dinghy README.
