### ISSUE TITLE
Is it possible to install Dinghy without Homebrew?

### ISSUE THREAD

**Issue by ycherfan** [codekitchen/dinghy#174]
Is there a way to install Dinghy on OS X without Homebrew? I use MacPorts, so I don't have Homebrew installed.

Thanks in advance.

**Comment by codekitchen** [comment]
Not currently no. MacPorts support sounds fine to me, if you'd like to add it. Alternatively you could install homebrew using a different prefix, if you don't want it touching `/usr/local`.

**Comment by codekitchen** [comment]
I'm going to close this, as it's not something I plan to add support for.
