### ISSUE TITLE
brew install error

### ISSUE THREAD

**Issue by webkul** [codekitchen/dinghy#175]
vipinsahu$ brew install https://github.com/codekitchen/dinghy/blob/master/cli/dinghy.rb
######################################################################## 100.0%
Error: /Library/Caches/Homebrew/Formula/dinghy.rb:5: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/Library/Caches/Homebrew/Formula/dinghy.rb:6: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/Library/Caches/Homebrew/Formula/dinghy.rb:6: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">
                     ^
Please report this bug:
    https://git.io/brew-troubleshooting

**Comment by ryansch** [comment]
That's not how brew works.  Use:

```sh
$ brew tap codekitchen/dinghy
$ brew install dinghy
```

**Comment by codekitchen** [comment]
Did you get that command from somewhere? Please follow the install instructions [in the README](https://github.com/codekitchen/dinghy#install).
