### ISSUE TITLE
Lack of understanding of use of host names with docker compose

### ISSUE THREAD

**Issue by fatlazycat** [codekitchen/dinghy#179]
Hi, very handy project - thanks !
Had one issue - probably my lack of understanding.

Had a working etcd 3 node cluster that can be seen from 

https://gist.github.com/fatlazycat/62ccda378e5b294fd4ea7701426c797c

after using dinghy I was surprised that it stopped working - seemed to be unable to resolve the hosts within docker-compose.

To get it to work in dinghy I had to externalise all ports and use external host names as per

https://gist.github.com/fatlazycat/ce5fecf12a955ecdfd4b9edabed1a389

Ignore the rename of the SSL certs. Had the same issues with / without SSL.

I must be missing something ?!!?

Thanks

**Comment by codekitchen** [comment]
Dinghy just uses docker-machine underneath, and I don't see any reason your first compose file shouldn't work. What errors were you hitting?

**Comment by fatlazycat** [comment]
Errors such as 

```
etcd1    | 2016-05-05 09:51:28.058717 E | rafthttp: failed to find member 96d27a526d4a1d91 in cluster 9364bfb239522e45
etcd1    | 2016-05-05 09:51:28.058917 D | rafthttp: failed to dial e5dff7e9e7e4c257 on stream MsgApp v2 (remote member e5dff7e9e7e4c257 could not recognize local member)
etcd1    | 2016-05-05 09:51:28.073498 E | rafthttp: failed to find member 96d27a526d4a1d91 in cluster 9364bfb239522e45
etcd1    | 2016-05-05 09:51:28.074116 E | rafthttp: failed to find member 96d27a526d4a1d91 in cluster 9364bfb239522e45
etcd1    | 2016-05-05 09:51:28.074606 D | rafthttp: failed to dial 45acc12b58db2d17 on stream MsgApp v2 (remote member 45acc12b58db2d17 could not recognize local member)
etcd1    | 2016-05-05 09:51:28.074883 D | rafthttp: failed to dial 45acc12b58db2d17 on stream Message (remote member 45acc12b58db2d17 could not recognize local member)
etcd1    | 2016-05-05 09:51:28.149089 E | rafthttp: streaming request ignored (ID mismatch got 45acc12b58db2d17 want 96d27a526d4a1d91)
etcd1    | 2016-05-05 09:51:28.149561 E | rafthttp: streaming request ignored (ID mismatch got 45acc12b58db2d17 want 96d27a526d4a1d91)
etcd1    | 2016-05-05 09:51:28.162450 E | rafthttp: streaming request ignored (ID mismatch got e5dff7e9e7e4c257 want 96d27a526d4a1d91)
etcd2    | 2016-05-05 09:51:28.162944 E | rafthttp: failed to dial e5dff7e9e7e4c257 on stream Message (unhandled error "to field mismatch\n" when precondition failed)
etcd2    | 2016-05-05 09:51:28.163052 I | rafthttp: the connection with e5dff7e9e7e4c257 became inactive
```

**Comment by codekitchen** [comment]
Yeah it's all just layered on top, nothing funky like that. I'm not familiar with etcd so I can't say for certain what those errors are about, but it seems unlikely to be caused by dinghy. We have dozens of docker-compose based projects that have containers talking to each other directly over the docker networks in this way.

**Comment by fatlazycat** [comment]
Yeah odd, wasn’t what I was expecting. Thanks
