### ISSUE TITLE
Arbitrary port mapping.

### ISSUE THREAD

**Issue by squaresurf** [codekitchen/dinghy#18]
It is really nice to be able to have `VIRTUAL_PORT` map to the http port.

What I would like is to be able to use this same functionality for any port. For example, a mysql docker box. I want to be able to expose the mysql port 3306 without specifying what port it should be mapped. This request would support that.

**Comment by codekitchen** [comment]
Unless I'm misunderstanding, isn't this just the `docker run --publish` option? Or are you looking to have ports listen on the host machine itself, unlike `VIRTUAL_PORT` which listens on the VM's interface? That's discussed in #20 as well.

**Comment by squaresurf** [comment]
Yes #20 is the same thing as this.
