### ISSUE TITLE
Support for Docker for Mac/Windows

### ISSUE THREAD

**Issue by marclennox** [codekitchen/dinghy#180]
I've been using the new Docker for Mac beta (https://blog.docker.com/2016/03/docker-for-mac-windows-beta/), which nicely packages the docker environment on OSX and Windows (VM, client, engine, etc.).

Based on what I'm seeing, this will very quickly be the preferred way to run Docker.  That being said, there are 2 things which Dinghy provides which makes Docker development (on any platform) much better, that being the nginx proxy and dns server.

How difficult would it be to allow the dinghy CLI to specify which components to run, such that if you were running Docker for Mac, you could run the DNS and proxy portions only.

**Comment by codekitchen** [comment]
Yeah, the eventual plan is to deprecate Dinghy once Docker for Mac is more stable and performant. We're tracking that in https://github.com/codekitchen/dinghy/issues/166

The HTTP proxy has already been split out into an independent project, I've got people using it on both Linux with native Docker and OS X with Docker for Mac. See the README https://github.com/codekitchen/dinghy-http-proxy#os-x

I probably won't ever adapt Dinghy itself to do that setup, but I may create a new script at some point to do it.

**Comment by marclennox** [comment]
Thanks Brian.  I will try to use the proxy alone.  Thanks for all your work on dinghy!

Sent from Outlook Mobile




On Thu, May 5, 2016 at 8:07 AM -0700, "Brian Palmer" <notifications@github.com> wrote:












Yeah, the eventual plan is to deprecate Dinghy once Docker for Mac is more stable and performant. We're tracking that in #166



The HTTP proxy has already been split out into an independent project, I've got people using it on both Linux with native Docker and OS X with Docker for Mac. See the README https://github.com/codekitchen/dinghy-http-proxy#os-x



I probably won't ever adapt Dinghy itself to do that setup, but I may create a new script at some point to do it.

**Comment by marclennox** [comment]
dinghy-http-proxy works great with Docker for Mac, and because DFM exposes ports to the host, you don't need to know the VM IP, just use the linux instructions to run the proxy.

**Comment by codekitchen** [comment]
Oh good point, I'll add it to those README instructions. Thanks.

**Comment by codekitchen** [comment]
I've opened an issue in that project to track adding an installation script of some sort, so I'm going to close this. Thanks.

https://github.com/codekitchen/dinghy-http-proxy/issues/6
