### ISSUE TITLE
DNS Server Fails To Resolve MX Records, This Works in Boot2Docker

### ISSUE THREAD

**Issue by devonhumes** [codekitchen/dinghy#185]
Resolving an MX record fails to work inside of a dinghy VM, but it does work inside of the latest boot2docker VM.

Command to run:
```
docker run -it debian bash -c "apt-get update && apt-get install dnsutils -y && dig mx ASPMX.L.GOOGLE.com"
```

Output from Dinghy:
```
; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> mx ASPMX.L.GOOGLE.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOTIMP, id: 31527
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ASPMX.L.GOOGLE.com.		IN	MX

;; Query time: 4 msec
;; SERVER: 10.0.2.3#53(10.0.2.3)
;; WHEN: Wed May 25 13:16:05 UTC 2016
;; MSG SIZE  rcvd: 47
```

Output from Boot2Docker:
```
; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> mx ASPMX.L.GOOGLE.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3352
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;ASPMX.L.GOOGLE.com.		IN	MX

;; AUTHORITY SECTION:
L.GOOGLE.com.		30	IN	SOA	ns1.GOOGLE.com. dns-admin.GOOGLE.com. 123202217 900 900 1800 60

;; Query time: 43 msec
;; SERVER: 10.0.2.3#53(10.0.2.3)
;; WHEN: Wed May 25 13:16:57 UTC 2016
;; MSG SIZE  rcvd: 86
```

Lacking this makes it impossible to run any container which requires MX lookups (i.e. postfix) from inside of dinghy without first setting the `--dns` docker option. If that option is provided then it works as expected.

**Comment by codekitchen** [comment]
You didn't say what VM provider you're using, but I'm guessing it's VirtualBox? This sounds like a dup of https://github.com/codekitchen/dinghy/issues/172 , VirtualBox's host DNS resolver doesn't support all record types.

Lately I've been using the xhyve driver, your test case works there. So that's one option if you want an immediate fix.

**Comment by devonhumes** [comment]
You're right that it is VirtualBox, but I don't think it's a duplicate of
#172. It is working with the default docker-machine VM on VirtualBox. I
might be missing something, but if it was an issue with VirtualBox wouldn't
it affect the default docker-machine VM as well?

**Comment by codekitchen** [comment]
No, dinghy sets the `natdnshostresolver1` option in VirtualBox (to make the `*.docker` DNS resolution work) while docker-machine does not.

**Comment by devonhumes** [comment]
Ah, my mistake.
