### ISSUE TITLE
Sending build context to Docker daemon is slow

### ISSUE THREAD

**Issue by BastianHofmann** [codekitchen/dinghy#19]
When I run a `docker build` the `Sending build context to Docker daemon` step is slow. It always loads a few MB then it stops for a few seconds before it starts loading the next few MBs.

OSX 10.10.3
Vagrant 1.7.2
VirtualBox 4.3.20
Docker version 1.5.0, build a8a31ef

**Comment by codekitchen** [comment]
Is this specific to one project, or are you seeing this behavior across all docker builds? I'm not aware of anybody else who has run into this. I had one other report of something similar a while back, but it turned out the project just had huge `.git` and `node_modules` dirs that weren't in `.dockerignore`.

**Comment by BastianHofmann** [comment]
In this case I'm sendibg abou 250mb. It worked fine with boot2docker.

**Comment by lmakarov** [comment]
Had the same issue, see https://github.com/blinkreaction/boot2docker-vagrant/issues/13 for a solution.

**Comment by codekitchen** [comment]
Oh that's a great tip, thanks @lmakarov 

I'll get this into the next release, in the meantime @BastianHofmann you could manually add this fix to `/usr/local/var/dinghy/vagrant/Vagrantfile`. I'd love to hear if that solves it for you.

**Comment by BastianHofmann** [comment]
Will do.

**Comment by BastianHofmann** [comment]
Works great!

**Comment by codekitchen** [comment]
Hooray! VM networking is still mostly a mystery to me, I'm afraid. I'll get this fix in.

**Comment by eibrahim** [comment]
I fixed it by moving my Dockerfile and docker-compose.yml into a subfolder called docker and it worked.  Apparently docker sends the current folder to the daemon and my folder was 9 gigs.

**Comment by lmakarov** [comment]
@eibrahim If you don't want Docker to pick up your entire folder during the build, you can use a .dockerignore file - https://docs.docker.com/reference/builder/#dockerignore-file

E.g., `.dockerignore`:
```
*
```

**Comment by eibrahim** [comment]
Great tip. Didn't think of adding * to .dockerignore. Thanks.

**Comment by kvz** [comment]
Adding to this you can use

```
*
!stack.statuspage
```

to create a whitelist, vs a blacklist.
