### ISSUE TITLE
--no-proxy flag not working any more?

### ISSUE THREAD

**Issue by ClydeCarr** [codekitchen/dinghy#193]
Just installed dinghy from homebrew on a new macbook pro today. Having a problem where the http proxy is started even though I specify the --no-proxy flag that used to work? Running dinghy 4.4.0

```
MacBook-Pro:test dan$ dinghy up --no-proxy
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/dancarr
Starting the FsEvents daemon
Starting DNS
2dad110e202c1341d240d542df3d153d5c08a5a0b60584205e21ccb1b00c1a42
   VM: running
  NFS: running
 FSEV: running
PROXY: running

Your environment variables are already set correctly.
MacBook-Pro:test dan$ dinghy version
Dinghy 4.4.0
```

**Comment by codekitchen** [comment]
Ah yeah, I need to do some renaming. That container runs both proxy and DNS now, so dinghy starts it for DNS even if you specify `--no-proxy`. Basically all that option does it disables forwarding ports 80 and 443, so that you can run something else on those ports.

**Comment by codekitchen** [comment]
The next version of dinghy will show separate status lines for `DNS` and `PROXY`, even though they run in the same container
