### ISSUE TITLE
Upgrade to pre-release boot2docker.iso

### ISSUE THREAD

**Issue by aaronjensen** [codekitchen/dinghy#196]
I'm trying to upgrade to 1.12.0-rc2 and doing a `dinghy upgrade` doesn't give me the prerelease. This is apparently similar to the docker-machine behavior, but it's unfortunate. I believe I can recreate my vm, but it'd be great if I could upgrade and specify a url. Or is there another way this should work?

Thanks!

**Comment by codekitchen** [comment]
It's a pain right? I don't know of any way to upgrade the VM and specify a URL, I tried to do that a while back but after not finding a solution I ended up just re-creating the VM. That capability would likely have to be added in docker-machine, not dinghy.

**Comment by aaronjensen** [comment]
Yeah, that's sort of what it was looking like. Oh well. Thanks for dinghy btw, it prevented us from abandoning docker. Docker for mac's performance is wild bad. Also the dinghy proxy is awesome.
