### ISSUE TITLE
Create fails on macOS Sierra beta 2

### ISSUE THREAD

**Issue by roderik** [codekitchen/dinghy#199]
I know, beta, but hoping someone will know what's up :)

- macOS Sierra beta 2
- dinghy 4.4.1
- vmware, but also xhyve and virtualbox

```
$ dinghy create --provider vmware -m 2048 -c 2 -d 50000
Creating the dinghy VM...
Error with pre-create check: "unexpected EOF"
/usr/local/Cellar/dinghy/4.4.1/cli/dinghy/machine.rb:22:in `create': There was an error creating the VM. (RuntimeError)
	from /usr/local/Cellar/dinghy/4.4.1/cli/cli.rb:59:in `create'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:12:in `<main>'
```

**Comment by codekitchen** [comment]
hey @roderik I don't have Sierra to test on, but this is definitely a docker-machine issue. You should be able to repro outside of dinghy with `docker-machine create -d vmwarefusion ...`. You'll need to file an issue with them, if there isn't one already.

**Comment by codekitchen** [comment]
Did you end up filing an issue with docker-machine? I'm going to close this issue as there isn't anything we can do in the dinghy project to fix it.
