### ISSUE TITLE
https proxy support

### ISSUE THREAD

**Issue by codekitchen** [codekitchen/dinghy#2]
https://github.com/jwilder/nginx-proxy already has HTTPS support, it's just not seamless enough for a development environment. I'd like to make it unnecessary to manually generate a self-signed cert for each app. Maybe just a default cert for all apps, the domain mismatch isn't a huge deal if the cert will have to be manually accepted anyway.

**Comment by idyll** [comment]
To address this would you consider supporting a different domain structure? 

I assume that the issue is that you can't get a browser to trust a wildcard on a TLD, like *.docker.
You can issue a wildcard certificate to *.dock.er that browsers will trust. (Not saying I like app.dock.er, just that you can use a wildcard at that point.)

Thanks for the great project, by the way. :)

**Comment by codekitchen** [comment]
That's a great point, I actually hadn't considered it that far yet. Thanks, I agree that it's worth switching to a 2nd level domain to implement this in a seamless way.

**Comment by jamesottaway** [comment]
Just want to add a :+1: here, since I'm eagerly awaiting this feature.

In the interim, is there a manual approach I can use to mount my SSL certs/keys into Dinghy's running `nginx-proxy` container?

**Comment by Kenny-House** [comment]
Thought I might add, I believe a wildcard cert like `*.docker` is perfectly valid, it's just highly unusual to see.

**Comment by codekitchen** [comment]
The cert would be "valid", but most browsers are hard-coded to reject it anyway. See for instance http://security.stackexchange.com/questions/6873/can-a-wildcard-ssl-certificate-be-issued-for-a-second-level-domain

**Comment by Kenny-House** [comment]
Oh wow, the comments in the Chromium source seem to suggest that not only are second-level wildcard certs rejected, but any cert from a non-standard TLD is also rejected. 

https://chromium.googlesource.com/chromium/src/net/+/HEAD/cert/x509_certificate.cc#574

**Comment by mickaelperrin** [comment]
Thanks again for this great project. Until Docker will support natively Docker on Mac OS X, it's the only way to go when using large file sharing...

I understand that https support of jwilder/nginx-proxy  is not as straightforward as it should be especially for a development environment. However, complex support would be better that no support at all.

How would you recommended the use of https with dinghy ? By-pass the dinghy nginx-proxy and use it directly in our containers ?

I look at the [codekitchen/dinghy-http-proxy](https://github.com/codekitchen/dinghy-http-proxy/), it seems that the support of https has been removed in the nginx [templates](https://github.com/codekitchen/dinghy-http-proxy/blob/master/nginx.tmpl#L52) files, and [the http_proxy.rb file mention certificates](https://github.com/codekitchen/dinghy/blob/master/cli/dinghy/http_proxy.rb#L24) but do not mount the port 443. Would it be much more difficult than reuse the original Nginx templates files regarding SSL support to reactivate it ?

To go further, and regarding the previous posts, the use of a wildcard *.docker seems to be difficult. Why about the generation of self-signed wildcard domain by changing the dinghy_domain variable ? Or what about auto-generating trusted certificates from [let's encrypt](https://letsencrypt.org/) like the project [https portal](https://github.com/SteveLTN/https-portal) does ?

**Comment by mickaelperrin** [comment]
Just added two pull requests to implement a basic https support in the way jwilder/nginx-proxy did. I think I backported only what was needed for single host certificate files (no wildcard or SNI).

- [Patch for dinghy ](https://github.com/codekitchen/dinghy/pull/168)
- Patch for [dinghy_http_proxy](https://github.com/codekitchen/dinghy-http-proxy/pull/4)

**Comment by codekitchen** [comment]
Thanks again for the work there. I'm going to close this, and open a separate issue for auto-generating certs, if we ever want to tackle that.
