### ISSUE TITLE
Suspend the dinghy VM

### ISSUE THREAD

**Issue by vladfr** [codekitchen/dinghy#200]
Is there a way to suspend the VM, rather than stopping it? I'm using it with vbox.

**Comment by codekitchen** [comment]
There's no suspend command in `docker-machine`, so Dinghy doesn't support it either. In theory you could use the virtualbox UI or the VBoxManage CLI command to suspend the machine, but I've never really experimented with that approach. If you're interested in seeing this added, file an issue on the docker-machine side and see if they are interested.
