### ISSUE TITLE
Connecting to dinghy with no outgoing network connection? (offline)

### ISSUE THREAD

**Issue by Ghazgkull** [codekitchen/dinghy#201]
Is there a way to take your machine offline and continue using dinghy?

Prepping for a camping trip, I tried disabling wifi to make sure I'd still be able to work against my local dinghy server. But my browsers (Chrome/FF/Safari) all refused to even try connecting to the server, complaining that my MacBook had no network connection. I've found the same thing happens if wifi is enabled but I'm not connected to any network (option+click on the network icon in the toolbar and the Disconnect option appears).

Is this a side-effect of the way dinghy integrates its DNS server into the MacOS host? Is there any kind of workaround or will MacOS just not even try to resolve names when it has no network?

**Comment by codekitchen** [comment]
Yeah I had a co-worker run into this once, OS X appears to not even try to use the resolvers defined in `/etc/resolver/*` if the computer doesn't have a network connection. We haven't come up with a solution, unfortunately.

Although, I did a quick search and pow, which uses the same mechanism, has a suggested workaround of creating an ad-hoc wifi network: https://github.com/basecamp/pow/wiki/Troubleshooting#cant-access-hosts-while-offline-on-os-x

Does that work for you?

**Comment by Ghazgkull** [comment]
Thanks for the quick reply, but unfortunately those workarounds don't work. From the discussion, it seems like the ad-hoc wifi network solution worked best before Mac OS Lion.

Guess I'll just use `dinghy ip` and adding those entries to `/etc/hosts`.

**Comment by codekitchen** [comment]
Ah, dang. I know that the `powder` utility for `pow` has a command to add all the hosts to `/etc/hosts` that was added at least partially in response to this problem. Something similar could be added for dinghy, but I sure wish OS X would release a fix.

**Comment by codekitchen** [comment]
Hm I just tried turning off wifi in macOS Sierra and I was still able to resolve `*.docker` using the command line, however safari and chrome still don't even try to connect.

I'm going to close this as there's not much we can do to fix that.
