### ISSUE TITLE
Multiple vm's, some work, some show an nginx 404 message

### ISSUE THREAD

**Issue by rstudner** [codekitchen/dinghy#204]
I have multiple containers (8).. almost all of them have rails apps inside.

5 of them, I hit the IP & port, and it responds perfect.  3 of them, I hit the IP & Port and I see an nginx 404 error (I'm used to seeing nginx 502's when things can't talk).

One thing I noticed (odd) is that if I go into my docker-compose.yml and comment out:

```
  volumes:
  - ".:/src"
```

Then it all works.

So for some reason, making it so my local file system in available to that container breaks it.

(this doesn't happen if I just do docker/VB without dinghy.  everything works fine).

**Comment by codekitchen** [comment]
I'm guessing that since you say you are hitting "the IP & port" for your containers, you aren't using the dinghy HTTP proxy to access them, but you're hitting them directly? The 404 error may be coming from dinghy's HTTP proxy. Are your other containers trying to expose port 80 or 443 to the host VM? That would conflict with the HTTP proxy (which can be disabled if you aren't planning to use it).

**Comment by rstudner** [comment]
Yeah, basically there are like 5 rails apps.

the "web app" is port 3000
a couple "services apps" are 4000, 5000 etc.

I can do 192.168.99.101:3000 and get the 404
but 192.168.99.101:4000 gets a rails app
:5000 gets a rails app

And oddly, if I remove:
```
  volumes:
  - ".:/src"
```
From the app hiding behind the exposed 3000 port... it then works hah.

**Comment by rstudner** [comment]
Just checked.. this is my preferences.yml:

```
:preferences:
  :proxy_disabled: false
  :fsevents_disabled: false
  :machine_name: dev
```

**Comment by codekitchen** [comment]
The proxy container also runs DNS, so even if you disable the proxy it runs the dns portion of that container. It's confusing, I've already made a change on master to show separate statuses for DNS and PROXY to help clear things up.

**Comment by codekitchen** [comment]
Hey I'm going to close this as I think the original concern was resolved, feel free to re-open if needed.
