### ISSUE TITLE
Set Custom Mounting Volume

### ISSUE THREAD

**Issue by Johnb21** [codekitchen/dinghy#205]
When you create a new dinghy container - it defaults to "/Users/<user>". However, if I have my code elsewhere and not within this directory on my machine, I continuously get errors unless I move the code I build for my container into the "/Users/<user>" directory.

There should be an option to set the mount volume and not force that user directory.

**Comment by codekitchen** [comment]
I merged a PR a while back that adds support for this via env vars, see https://github.com/codekitchen/dinghy/blob/master/cli/dinghy/unfs.rb#L50 , but it doesn't look like it got documented. I'd like to see it moved to the `~/.dinghy/preferences.yml` preferences file, instead, but I'll add some documentation for that current solution.
