### ISSUE TITLE
Files not sent to the container if the size did not change

### ISSUE THREAD

**Issue by ckald** [codekitchen/dinghy#206]
When edit some files on the host (my app's code), I noticed that containers do not notice this until I change the size of the file (i.e., the number of letters). This is super annoying because usually I need to play with some numbers and this defeats the purpose of my hot-reload JS server.

Previously I used vanilla boot2docker and while it had some latency in file sharing, I never seen such a pronounced issue. Other people at my company never encountered this, so I'm thinking this is something with dinghy

Here's my setup:

```
➜  project git:(master) ✗ docker -v
Docker version 1.11.1, build 5604cbe
➜  project git:(master) ✗ docker-compose -v
docker-compose version 1.8.0, build 94f7016
➜  project git:(master) ✗ dinghy -v
Dinghy 4.4.1
```

**Comment by codekitchen** [comment]
Hi @ckald , what framework are you using for hot reloading? My first guess would be that this is the same issue as https://github.com/codekitchen/fsevents_to_vm/issues/7. There's a proposed fix there, but nobody has had a chance to implement it yet.

**Comment by codekitchen** [comment]
Closing in favor of https://github.com/codekitchen/dinghy/issues/264
