### ISSUE TITLE
http proxy stopped working few days ago

### ISSUE THREAD

**Issue by jaequery** [codekitchen/dinghy#207]
Hi guys, just a few days ago, noticed that the http proxy provided by dinghy stopped working. It'd just show Nginx default page. If i stop the dinghy http proxy and just run jwilders proxy manually, it works. This happened also with other co-workers as well. Any idea why?

**Comment by codekitchen** [comment]
Please paste the output of running `docker exec -it dinghy_http_proxy cat /etc/nginx/conf.d/default.conf`, which will be the proxy's nginx config. My first guess would be that you're not hitting the correct domain name for your container. That used to work by accident, and will still work with the jwilder proxy, because nginx was configured to just proxy to the first defined server for any unknown hostname. What hostname are you trying to hit, and what is the `VIRTUAL_HOST` env var you've defined for your container?

**Comment by jaequery** [comment]
` ~/Sites/bambee/bambee.com ‹master M⁇› » docker exec -it dinghy_http_proxy cat /etc/nginx/conf.d/default.conf
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
upstream *.ngrok.io {
       	server 172.17.0.7:3000;
}
server {
       	server_name *.ngrok.io;
       	listen 80;
       	access_log /var/log/nginx/access.log vhost;
       	location / {
       		proxy_pass http://*.ngrok.io;
       	}
}
upstream bambee.docker {
       	server 172.17.0.2:3000;
       	server 172.17.0.3:3000;
}
server {
       	server_name bambee.docker;
       	listen 80;
       	access_log /var/log/nginx/access.log vhost;
       	location / {
       		proxy_pass http://bambee.docker;
       	}
}
upstream bambeecom.docker {
       	server 172.17.0.7:3000;
}
server {
       	server_name bambeecom.docker;
       	listen 80;
       	access_log /var/log/nginx/access.log vhost;
       	location / {
       		proxy_pass http://bambeecom.docker;
       	}
}
upstream staging.bambee.com {
       	server 172.17.0.7:3000;
}
server {
       	server_name staging.bambee.com;
       	listen 80;
       	access_log /var/log/nginx/access.log vhost;
       	location / {
       		proxy_pass http://staging.bambee.com;
       	}
}
upstream webpack.bambee.com {
       	server 172.17.0.8:8080;
}
server {
       	server_name webpack.bambee.com;
       	listen 80;
       	access_log /var/log/nginx/access.log vhost;
       	location / {
       		proxy_pass http://webpack.bambee.com;
       	}
}
upstream webpack.bambeecom.docker {
       	server 172.17.0.8:8080;
}
server {
       	server_name webpack.bambeecom.docker;
       	listen 80;
       	access_log /var/log/nginx/access.log vhost;
       	location / {
       		proxy_pass http://webpack.bambeecom.docker;
       	}
}
upstream www.bambee.docker {
       	server 172.17.0.3:3000;
}
server {
       	server_name www.bambee.docker;
       	listen 80;
       	access_log /var/log/nginx/access.log vhost;
       	location / {
       		proxy_pass http://www.bambee.docker;
       	}
}
upstream app.bambeecom.docker {
       	server 172.17.0.7:3000;
}
server {
       	server_name app.bambeecom.docker;
       	listen 80;
       	access_log /var/log/nginx/access.log vhost;
       	location / {
       		proxy_pass http://app.bambeecom.docker;
       	}
}
upstream db.bambeecom.docker {
       	server 172.17.0.5:5432;
}
server {
       	server_name db.bambeecom.docker;
       	listen 80;
       	access_log /var/log/nginx/access.log vhost;
       	location / {
       		proxy_pass http://db.bambeecom.docker;
       	}
}
upstream memcache.bambeecom.docker {
       	server 172.17.0.6:11211;
}
server {
       	server_name memcache.bambeecom.docker;
       	listen 80;
       	access_log /var/log/nginx/access.log vhost;
       	location / {
       		proxy_pass http://memcache.bambeecom.docker;
       	}
}
upstream webpack.bambeecom.docker {
       	server 172.17.0.8:8080;
}
server {
       	server_name webpack.bambeecom.docker;
       	listen 80;
       	access_log /var/log/nginx/access.log vhost;
       	location / {
       		proxy_pass http://webpack.bambeecom.docker;
       	}
}
upstream www.prelaunch.docker {
       	server 172.17.0.2:3000;
}
server {
       	server_name www.prelaunch.docker;
       	listen 80;
       	access_log /var/log/nginx/access.log vhost;
       	location / {
       		proxy_pass http://www.prelaunch.docker;
       	}
}`

I'm trying to hit http://bambee.docker/ thanks!

**Comment by codekitchen** [comment]
It looks like you're running an older version of dinghy, which means my first guess doesn't apply. You should update to the latest dinghy, which adds a proxy landing page which might help a bit with troubleshooting.

Have you verified whether the nginx default page is coming from the dinghy http proxy, or whether it's coming from a process running in your bambee.docker container?

```
upstream bambee.docker {
        server 172.17.0.2:3000;
        server 172.17.0.3:3000;
}
```

That looks like you've got two containers running both with VIRTUAL_HOST set to `bambee.docker`. So nginx is going to cycle between them for each request. Is that intentional? If one of them isn't responding to HTTP requests, you'd see the nginx page.

**Comment by codekitchen** [comment]
I'm going to close this issue since there hasn't been any recent activity, please re-open if you are still seeing the problem.
