### ISSUE TITLE
Configurable network address range

### ISSUE THREAD

**Issue by ginkel** [codekitchen/dinghy#208]
AFAICS dinghy currently always uses 192.168.99.0/24 as the host-only network. Is there a way to override this or make it configurable in case 192.168.99.0/24 is already in use for the LAN?

**Comment by codekitchen** [comment]
It's not always `192.168.99.0/24`, it's whatever docker-machine chooses, which as far as I know means it's whatever vmware/virtualbox/xhyve chooses. I've actually never looked into whether docker-machine has configuration options for that. If it does, we could implement https://github.com/codekitchen/dinghy/issues/122 to allow using those options with `dinghy create`.

**Comment by bvogel** [comment]
Actually there IS a configuration option, it's `--virtualbox-hostonly-cidr`

**Comment by codekitchen** [comment]
Perfect, I'm going to close this in favor of #122 then.
