### ISSUE TITLE
dinghy http proxy: bind for 0.0.0.0:19322 failed

### ISSUE THREAD

**Issue by ryansch** [codekitchen/dinghy#210]
Full error:

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint dinghy_http_proxy (a10140c1381fb4636911f2fbf199ffa5186510870d290d354ad1e6b0888e8bde): Bind for 0.0.0.0:19322 failed: port is already allocated.
```

I get this about 50% of the time when running `dinghy up`.  Running `dinghy stop` followed by `dinghy up` fixes it.  I've only seen this pop up since upgrading to macOS Sierra.

I can open this against [codekitchen/dinghy-http-proxy](https://github.com/codekitchen/dinghy-http-proxy) if that makes more sense.

**Comment by codekitchen** [comment]
Hm, that's Docker saying that another container already has grabbed host UDP port 19322. Probably not, but just to check, you don't have any other containers using that port? On every `dinghy up`, it deletes the HTTP proxy container and re-creates it. I wonder if there's a race condition with that, where the port doesn't get "freed" by docker before we try to grab it again.

**Comment by SeerUK** [comment]
Just to add a little bit more information here, I'm still on El Capitan, and am experiencing this. I don't think it's anything to do with the upgrade to macOS Sierra. I suspect that your theory is correct @codekitchen.

**Comment by ryansch** [comment]
It happens a lot less often now but I do run into this about once every other week (better than once a day!).

**Comment by codekitchen** [comment]
I have a sneaking suspicion that we're making the problem worse by doing a `docker rm -f` rather than deleting the container more gracefully. Rather than adding a sleep/retry loop (bleh), I'm going to try this first: https://github.com/codekitchen/dinghy/commit/b584148adee6de40b9e56cc461bdfe3430a0b6dd

**Comment by codekitchen** [comment]
That change has been released in v4.4.2, let me know if you still run into this

**Comment by wateryoma** [comment]
just want to mention - I had similar issue (dinghy proxy and dns was stopped) - removing conflicting entries in my /etc/hosts solved it.

**Comment by codekitchen** [comment]
I'm going to consider this fixed by that change, feel free to re-open if anybody is running into this still.
