### ISSUE TITLE
Performance Issues with shared host volumes on macOS Sierra 10.12

### ISSUE THREAD

**Issue by walterra** [codekitchen/dinghy#212]
Since upgrading to macOS Sierra 10.12 I have issues with the performance of shared host directories. I'm using dinghy with docker-compose to run a build of JavaScript files using RequireJS and it's optimization option. (Unfortunately I can only guess that the performance degradation is related to the OS update since that's the only thing I changed about the setup).

I reinstalled dinghy, reinstalled the VM, completely purged docker/docker-compose and reinstalled via brew to no avail.

- Dinghy 4.4.1
- Docker version 1.12.1, build 23cf638
- docker-compose version 1.8.0, build unknown
- I tried with provider `vmwarefusion` and `virtualbox`

`dinghy status` says VM/NFS/FSEV/PROXY is running.

Previously the build process took about 20-30 seconds, now it's about 10 minutes.

I guess it's a bit of a vague report. Do you have suggestions what I could do so we can pin down and identify the bottleneck?

**Comment by codekitchen** [comment]
Hm first thing I would check is if the NFS mount is actually getting used, rather than built-in file sharing. Running `dinghy ssh mount | grep /Users` should show "/Users/<you>" mounted via `type nfs`.

If that looks correct, check for any errors or odd messages in `/usr/local/Cellar/dinghy/<version>/local/var/dinghy-NFS.output`

You could try removing and then re-installing `unfs3` with brew, maybe Sierra is interacting badly with the previously-compiled code. That seems unlikely, though, since others haven't reported this.

**Comment by walterra** [comment]
Thanks for the quick reply.

The output of the `/Users` mount shows `type nfs`.

`192.168.38.1:/Users/<user> on /Users/<user> type nfs (rw,relatime,vers=3,rsize=32768,wsize=32768,namlen=255,hard,nolock,proto=udp,port=19275,timeo=7,retrans=3,sec=sys,local_lock=all,addr=192.168.38.1)`

I tried to do some benchmarks:

```
# write
$ dinghy ssh dd if=/dev/zero of=/Users/walterra/tempfile bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.0GB) copied, 27.955665 seconds, 36.6MB/s

# read
$ dinghy ssh dd if=/Users/walterra/tempfile of=/dev/null bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.0GB) copied, 201.712300 seconds, 5.1MB/s
```

(This is a MacBook Pro with SSD. Running the same `dd` commands directly on the host in the same directory does several hundred MB read/write speed.)

`dinghy-NFS.output` contains lots of `unable to send RPC reply` lines, looks like those happen when doing the read-benchmark, they don't show up doing the write-benchmark.

I remove/reinstalled `unfs3` but it didn't change anything.

**Comment by codekitchen** [comment]
Have you tried running your build process completely in-container, to compare it to the shared directory perf? It'd be good to rule out other causes.

Those numbers are lower but not too awfully different from what I see on my MBP, you won't see native performance over NFS:

```
dinghy ssh dd if=/dev/zero of=/Users/codekitchen/tempfile bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.0GB) copied, 17.668363 seconds, 58.0MB/s

dinghy ssh dd if=/Users/codekitchen/tempfile of=/dev/null bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.0GB) copied, 82.544413 seconds, 12.4MB/s
```

`unable to send RPC reply` is a pretty common error I've seen in lots of people's logs, but I don't know enough about nfs and unfs internals to know what frequency could be considered acceptable.

**Comment by walterra** [comment]
I did the benchmarks on a place on the VM's disk in the container and found out the results were pretty slow too! The VM used a non-pre-allocated disk. I converted it to pre-allocated and the performance increased luckily.

However, I finally found the real culprit: To debug a third party module I had to fetch its dev-depedencies some time ago. I just found out those were about 500MB of additional small files. While my build process actually didn't need those, it looks like they were at least attempted to read once when parsing the directories, resulting in the slowdown!

Deleting those files brought the build process up to it's old speed. So this was definitely not a problem on dinghy's side after all, guess you can close the issue!

Many thanks for the help :)

**Comment by codekitchen** [comment]
Cool, glad you got it fixed
