### ISSUE TITLE
How to start the services at login

### ISSUE THREAD

**Issue by rodrigoaguilera** [codekitchen/dinghy#221]
I want to have dinghy available as soon as I start my Mac. Is this possible?

Ideally it can be added to the FAQ :)

Thanks

**Comment by codekitchen** [comment]
This would be difficult right now because Dinghy requires `sudo` for a couple tasks, so you need user interaction. Maybe it could be made to work by running the entire `dinghy start` operation as root, but I don't think that would work today, it'd probably take some code changes.

**Comment by rodrigoaguilera** [comment]
Just what I imagined. I will report if I figure something out
