### ISSUE TITLE
Include a warning for preferences that have providers with invalid docker-machines

### ISSUE THREAD

**Issue by illegalnumbers** [codekitchen/dinghy#223]
Not sure how feasible this is but figured it was something I saw so it should probably be reported. If you have docker-machine installed on Mac OSX Sierra with Dinghy and configure your provider to be Parallels rather than using docker-machine-parallels it gives a bunch of unexpected behavior and things don't quite work correctly. It might be useful to give warnings in that instance or in the instance of using docker-machine instead of docker-machine-xhyve or if those executables are not installed.

**Comment by codekitchen** [comment]
Can you paste output of the unexpected behavior, or go into more detail on what exactly happens?

**Comment by illegalnumbers** [comment]
I can only speak from hearsay but it seemed as if images and volumes were having issues being persisted correctly. Dinghy seemed to have issues with one or more services stopping in the shell from time to time which was strange as well. Sorry on the lack of identifiable information.

**Comment by codekitchen** [comment]
Is there somebody else who can chime in here with more information, then? There's nothing actionable in this issue, yet.

Can you expand on `It might be useful to give warnings in that instance or in the instance of using docker-machine instead of docker-machine-xhyve or if those executables are not installed.`? I think part of the problem is I can't figure out what you're saying here. Also what does "providers with invalid docker-machines" mean in the issue title? Sorry if I'm being obtuse but I'm definitely not clear on what you're reporting.

**Comment by illegalnumbers** [comment]
No worries, honestly it was a bit unclear what the exact issue was that we were seeing but I kind of just guessed on it after we solved the issue. By "providers with invalid docker-machines" I was referring to a provider like Parallels which needs the special docker-machine-parallels to run properly (from the install steps https://github.com/codekitchen/dinghy#install). It seemed that the person who was having issues was having them because they were using regular docker-machine rather than docker-machine-parallels with that provider installed. 

I'll close the issue for now until I can get better information. Sorry for the confusion.

**Comment by codekitchen** [comment]
Ah OK. Did you confirm that they used `dinghy create -p parallels` to select the correct driver? That doesn't happen automatically. If that doesn't work it's likely an issue with docker-machine-parallels, but if we can get some output from the `dinghy create` command that'd help.

**Comment by illegalnumbers** [comment]
I believe so - the dinghy config files and preferences all looked like they were setup correctly but they didn't have docker-machine-parallels installed so that was the weird bit. It was like it somehow got around having that installed to create the VM and use it but there was some unexpected behavior after the fact.
