### ISSUE TITLE
Ishi - easily make your containers reachable from other machines on your LAN

### ISSUE THREAD

**Issue by suin** [codekitchen/dinghy#224]
This is not an issue but as I couldn't find out where to post my idea, I post here.

Today I made Ishi, which supports Dinghy developers. I am currently developing mobile web application in Dinghy environment. But it was hard to check my application from my iPhone, as the containers are not reachable from it.

Ishi is a simple command line tool which make your containers reachable beyond LAN by repeating HTTP requests from iPhone to containers in Dinghy.

## How to use

Start up dinghy:

```
$ dinghy up
$ eval $(dinghy env)
```

Create a container with `VIRTUAL_HOST`:

```
$ docker run -it --rm -e VIRTUAL_HOST=app.docker httpd:alpine
```

Start Ishi process on your Mac. When Ishi starts up, the listening port is shown in your console.

```
$ ishi app.docker
Listening on 127.0.0.1:8001
Fowarding to app.docker
```

Check IP address of Mac:

```
$ ifconfig
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	...
	inet 192.168.3.2 netmask 0xffffff00 broadcast 192.168.3.255
	...
```

Then visit `http://192.168.3.2:8001` from your mobile device on your LAN. Apache default page will be shown.

If you have interest with it, please see my repository: https://github.com/suin/ishi

**Comment by codekitchen** [comment]
That's cool, thanks @suin. This comes up a lot, especially with the QA department at my company, so I have a standard answer in the [Dinghy FAQ](https://github.com/codekitchen/dinghy/blob/master/FAQ.md#i-want-to-make-my-containers-reachable-from-other-machines-on-my-lan) to use [my-proxy](https://github.com/esnunes/my-proxy). I like that Ishi only forwards a specific hostname though, rather than blindly providing access to everything.

One question about your example, the output says `Listening on 127.0.0.1:8001` but if it was truly listening on `127.0.0.1` you wouldn't be able to access it from another device using IP `192.168.3.2`. I'm guessing that log line is incorrect?

**Comment by suin** [comment]
@codekitchen Thank you for giving feedback to my post.

I have read Dinghy FAQ before I make Ishi, and I know my-proxy is current solution. I have not tried it. It seems that my-proxy is a proxy, so that developers have to set up every mobile devices to make them reachables, isn't it? I felt this work a bit laborious.

As Ishi is a reverse proxy, once developers have set up on Desktop/Notebook, all mobile devices can reach contaieners. As you have pointed at, Ishi can deliver traffics against only single virtual host. 

When developers want to make multiple virtual host reachable, they have to start up multiple Ishi processes using different ports. For instance:

* 0.0.0.0:8000 -> app1.docker
* 0.0.0.0:8001 -> app2.docker
* 0.0.0.0:8002 -> app3.docker

This is limitation of Ishi.

About the output `Listening on 127.0.0.1:8001`, as you pointed at, Ishi listens on not only 127.0.0.1 but also LAN IP address like 192.168.3.2. Reading your question, I felt the output would make developers confuse. I would like to improve it. Would `Listening on port 8001` be better?

**Comment by codekitchen** [comment]
Yes, my-proxy is a proxy that needs to be configured on each device.

For the log output, I think either `Listening on 0.0.0.0:8001` or just `Listening on port 8001` would be fine, it just doesn't seem like a good idea to say `Listening on 127.0.0.1` when that's not what's actually happening.

Thanks again for the cool tool, if you want to send over a PR to add Ishi to the FAQ as another option that'd be great.

**Comment by suin** [comment]
Thank you for a lot of feedbacks!
I'll update Ishi to improve the log output.

**Comment by ceesvanegmond** [comment]
@suin @codekitchen Using ishi right now for accessing containers from mobile devices. Works great. I feel like my-proxy is a bit to complicated

**Comment by codekitchen** [comment]
I'm going to close this because of inactivity, but I'd still be happy to take a PR to add this to the FAQ/documentation.
