### ISSUE TITLE
write down the last worked docker and docker-xxx version

### ISSUE THREAD

**Issue by zjleon** [codekitchen/dinghy#225]
I got an error while creating a new vm machine:
```
Mounting NFS /Users/appledev114
Installing fsevents_to_vm, this will require sudo
ERROR:  While executing gem ... (NoMethodError)
    undefined method `size' for nil:NilClass
/usr/local/Cellar/dinghy/4.4.3/cli/dinghy/daemon.rb:60:in `system!': Error with the FsEvents daemon during installing (RuntimeError)
	from /usr/local/Cellar/dinghy/4.4.3/cli/dinghy/fsevents_to_vm.rb:35:in `install_if_necessary!'
	from /usr/local/Cellar/dinghy/4.4.3/cli/dinghy/fsevents_to_vm.rb:16:in `up'
	from /usr/local/Cellar/dinghy/4.4.3/cli/cli.rb:217:in `start_services'
	from /usr/local/Cellar/dinghy/4.4.3/cli/cli.rb:60:in `create'
	from /usr/local/Cellar/dinghy/4.4.3/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.4.3/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.4.3/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.4.3/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:12:in `<main>'
```
and I saw you have solve similar issue in https://github.com/codekitchen/dinghy/issues/107
and my error may related to docker-machine update

So Suggest you write the last tested docker version in the README, to avoid simulate issue rasied

**Comment by codekitchen** [comment]
Hey @zjleon, your error looks unrelated to #107. This is a failure while installing the `fsevents_to_vm` gem using the MacOS system ruby. Unfortunately it's not immediately clear to me what the error is. What version of Dinghy are you running?

The two shell commands that may have caused the error are:

    /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/gem list -i -v '~> 1.1.2' fsevents_to_vm

    sudo /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/gem install --no-rdoc --no-ri -n /usr/local/bin fsevents_to_vm -v '~> 1.1.2'

Can you run those two commands directly and paste the output? Maybe that'll help pinpoint the error.

**Comment by zjleon** [comment]
I found another solution and decide not to use dinghy, thx for helping
