### ISSUE TITLE
FsEvents fails to run when a non-system ruby is installed and in PATH

### ISSUE THREAD

**Issue by uberjay** [codekitchen/dinghy#227]
The fsevents_to_vm daemon fails to start because of a (reported) missing fsevents_to_vm gem:

```
⇒  dinghy restart
Stopping the FsEvents daemon
Stopping the dinghy VM...
Stopping NFS daemon, this will require sudo
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/huber
Starting the FsEvents daemon
Starting DNS and HTTP proxy
07286cae0065687413d2d303ee2a7c4132354577f3ab013f121bafb58c43f032
   VM: running
  NFS: running
 FSEV: stopped
  DNS: running
PROXY: running

FsEvents failed to run
details available in log file: /usr/local/Cellar/dinghy/4.4.3/local/var/dinghy-FsEvents.output

⇒  cat /usr/local/Cellar/dinghy/4.4.3/local/var/dinghy-FsEvents.output
/Users/huber/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'fsevents_to_vm' (>= 0) among 11 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/huber/.gem/ruby/2.3.0:/Users/huber/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /Users/huber/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /Users/huber/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/bin/fsevents_to_vm:22:in `<main>'
```

I... am not entirely sure what's happening. If I run `/usr/local/bin/fsevents_to_vm start /path/...`, it seems to start fine. I tried to fix this by hand, by installing the fsevents_to_vm gem in my user-installed ruby, but I see now that dinghy attempts to install gems in, and use the system default ruby. However, the binstub for fsevents_to_vm starts with `#!/usr/bin/env ruby`, so it's picking up my custom installed ruby.

If I run `dinghy up` from a clean shell without a modified `PATH`, `GEM_PATH`, etc., it works...

This is extremely strange... but look at the `GEM_PATH` reported in the backtrace:

`/Users/huber/.gem/ruby/2.3.0:/Users/huber/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0`

... and compare with my usual value:

```
/Users/huber/.gem/ruby/2.3.1:/Users/huber/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0
```

That first component is pointing to a non-existent directory when run from dinghy. Uhm... what?

This is, perhaps, a distraction from the (I believe) real issue, that the command should be executing using the system-installed ruby, but it is not. Am I correct?

**Comment by uberjay** [comment]
Oh wow... I think the confusion about `GEM_HOME` and `GEM_PATH` is actually a chruby bug. chruby is setting `GEM_HOME` to be `~/.gem/ruby/<VERSION>`, when it should be setting it to match what rubygems falls back to as its "user installation directory":

```
⇒  gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin16]
  - INSTALLATION DIRECTORY: /Users/huber/.gem/ruby/2.3.1
  - USER INSTALLATION DIRECTORY: /Users/huber/.gem/ruby/2.3.0

⇒  ruby -rrbconfig -e 'puts RbConfig::CONFIG["ruby_version"]'
2.3.0
⇒  ruby -e 'puts RUBY_VERSION'
2.3.1
```

...well... maybe it's not a bug, but it's certainly a mismatch over what directory to install gems in for a particular ruby version. When dinghy unsets `GEM_HOME`, rubygems falls back to looking in a directory named after the ruby ABI version, rather than the actual ruby release version.

In any case, I still believe the correct fix is to not be using any custom-installed ruby to begin with -- unsure how to correctly make that happen.

**Comment by uberjay** [comment]
As a final followup to myself (grin), a workaround is to unset `GEM_HOME`, and then install `fsevents_to_vm`. This way the gem is in a directory which will be searched when run inside the dinghy environment:

```
huber@lol:~|⇒  dinghy up
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/huber
Starting the FsEvents daemon
Starting DNS and HTTP proxy
5329ec372d4af940053a90bfe880b0594d9ed8b41dafcf3123beeb05d39b4408
   VM: running
  NFS: running
 FSEV: stopped
  DNS: running
PROXY: running

FsEvents failed to run
details available in log file: /usr/local/Cellar/dinghy/4.4.3/local/var/dinghy-FsEvents.output

Your environment variables are already set correctly.
huber@lol:~|⇒  dinghy stop
Stopping the FsEvents daemon
Stopping the dinghy VM...
Stopping NFS daemon, this will require sudo
huber@lol:~|⇒  (unset GEM_HOME GEM_PATH; gem install fsevents_to_vm)
Fetching: fsevents_to_vm-1.1.3.gem (100%)
Successfully installed fsevents_to_vm-1.1.3
Parsing documentation for fsevents_to_vm-1.1.3
Installing ri documentation for fsevents_to_vm-1.1.3
Done installing documentation for fsevents_to_vm after 0 seconds
1 gem installed
huber@lol:~|⇒  dinghy up
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/huber
Starting the FsEvents daemon
Starting DNS and HTTP proxy
bafc0d6ff29dea32447efae2dd675207236b7bb2fb58fa7bcdaeb929e7dd3932
   VM: running
  NFS: running
 FSEV: running
  DNS: running
PROXY: running

Your environment variables are already set correctly.
```

**Comment by codekitchen** [comment]
Hm, Dinghy already unsets `GEM_HOME` and `GEM_PATH` when it runs (see https://github.com/codekitchen/dinghy/blob/master/bin/dinghy) and it attempts to install fsevents_to_vm using the system ruby, rather than whatever ruby you have active through chruby (see https://github.com/codekitchen/dinghy/blob/master/cli/dinghy/fsevents_to_vm.rb#L32). Something about that doesn't seem to be working in your environment, though.

I'm not positive, but from the log output it looks like maybe dinghy is installing fsevents_to_vm using the system ruby, as designed, but then it is somehow trying to run fsevents_to_vm using your chruby install, or at least with some of that environment configured.

**Comment by uberjay** [comment]
Ah, I figured it out. I think. :)

I have the `--env-shebang` setting enabled in `~/.gemrc`, which rewrites the shebang line using /usr/bin/env. This has been helpful for switching back and forth between different ruby versions (e.g., as provided by homebrew, or installed with ruby-install). However, it seems like tho wrong thing for installing system ruby gems. I don't know if this is the proper way to ignore ~/.gemrc, but this works, and correctly leaves the shebang line pointing to the full path of the system ruby:

```
$ sudo /usr/bin/gem install --config-file '' fsevents_to_vm
Fetching: fsevents_to_vm-1.1.3.gem (100%)
Successfully installed fsevents_to_vm-1.1.3
Parsing documentation for fsevents_to_vm-1.1.3
Installing ri documentation for fsevents_to_vm-1.1.3
1 gem installed

$ head -n1 /usr/local/bin/fsevents_to_vm
#!/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
```

**Comment by uberjay** [comment]
Another option that seems to work is telling sudo to set `HOME`, so whatever customizations the user has in `~/.gemrc` are not found:

```
$ sudo -H /usr/bin/gem install fsevents_to_vm
```

This is ... possibly a better way to go? Seems like it'd be more guaranteed to give a clean environment unaffected by any other possible user configuration.

**Comment by codekitchen** [comment]
Oh dang I've never even heard of that rubygems flag. Thanks, moving the discussion over to that PR
