### ISSUE TITLE
Mounting NFS takes a long time

### ISSUE THREAD

**Issue by danny-balance** [codekitchen/dinghy#229]
Dinghy takes a very long time to come up (about 5 minutes), with the majority of the time stalling at the step `Mounting NFS /Users/xxx`. Is there anything I can do to debug/fix this?

```
→ /usr/bin/time dinghy up
...
299.03 real
```

MacOS v10.12.2
Dinghy v4.4.3

**Comment by codekitchen** [comment]
What VM provider are you using?

All Dinghy is doing at that step is running these three ssh commands into the VM to set up the NFS mount: https://github.com/codekitchen/dinghy/blob/master/cli/dinghy/machine.rb#L91

It could be indicative of some sort of issue with the virtual network interface, which I've seen happen to my co-workers once or twice before with Virtualbox. Does just a straight `dinghy ssh` take a long time as well? Or is the slowness specific to the `mount` command that reaches back out from the VM -> host.

You could try rebooting your Mac (sad I know) and see if that helps.

**Comment by danny-balance** [comment]
Yeah, I'm using VirtualBox (latest version, v5.1.12). `dingy ssh` is very quick, so it's not the actual SSH step which is hanging. This has been happening for a few weeks (new MBP), so it's definitely staying around after reboots.

I guess it must be something to do with the NFS mount step, although I'm not sure how to debug this any further. Is there anything I can check in VirtualBox?

**Comment by ryansch** [comment]
I've found it useful to debug the actual nfs mount command in isolation.  You should be able to ssh to the VM while it's hanging and run `ps` to grab the command.  Make sure you have a look at unfsd running on your mac as well.

**Comment by danny-balance** [comment]
Hey guys, I'll close this issue because I'm not sure I can debug any further, also seems like it's isolated to my machine only. Thanks for your help.
