### ISSUE TITLE
'dinghy create' reports incomplete usage information

### ISSUE THREAD

**Issue by nicolaiskogheim** [codekitchen/dinghy#230]
Consider this:

```sh
$ dinghy create --help
ERROR: "dinghy create" was called with arguments ["--help"]
Usage: "dinghy create"
```

Dinghy not accepting `--help` is okay, but it should say it accepts the `--provider=[virtualbox|xhyve|etc]` argument.

_____

```sh
$ dinghy version
Dinghy 4.4.1
```

**Comment by codekitchen** [comment]
Yeah I get tripped up by this even, and I'm the one who wrote it. It's a consequence of using [Thor](https://github.com/erikhuda/thor) for the CLI, I'm not aware of a way to change Thor's behavior here (you're supposed to use `dinghy help create` instead to see the available flags).

Maybe I can try just updating Dinghy to use the latest Thor, see if that improves the output.

**Comment by codekitchen** [comment]
Nope, upgrading to the latest Thor didn't change the output at all. I dug around the Thor docs a bit, but I don't see an obvious way to improve this behavior.

**Comment by nicolaiskogheim** [comment]
Thank you for looking into it.

We can keep an eye on this[1] issue. It's a couple of months old, but if it gets resolved, we can solve our issue too.

[1] https://github.com/erikhuda/thor/issues/532
