### ISSUE TITLE
Unable to create VM - DNS Issues

### ISSUE THREAD

**Issue by leian-ivey** [codekitchen/dinghy#237]
I get the following error message when starting dinghy vm

Starting the default VM...
Starting NFS daemon, this will require sudo
Password:
Waiting for NFS daemon...
Mounting NFS /Users/XXX-XXX
Starting the FsEvents daemon
Starting DNS and HTTP proxy
Unable to find image 'codekitchen/dinghy-http-proxy:2.5' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:50802->10.0.2.3:53: i/o timeout.
See 'docker run --help'.
   VM: running
  NFS: running
 FSEV: running
  DNS: stopped
PROXY: stopped

**Comment by alitain** [comment]
I got the the same error

**Comment by tylerssn** [comment]
I've been experiencing this as well. I'm new to docker, so I don't have much to add but am happy to help with whatever info I can. 

My inquiry into this is more related to why this happened rather than how to fix this. Resetting docker and rebooting resolved (if you want to call a reset "resolving") the DNS issue.

**Comment by codekitchen** [comment]
Was that using VirtualBox? When I've seen this in the past it's been because VB networking is sometimes broken on the newly created VM until a reboot, not anything Dinghy related. I'd love to find a fix but haven't ever had any luck.

**Comment by codekitchen** [comment]
I'm closing this for now, unless we can figure out why VirtualBox sometimes fails to fully initialize the virtual network until a MacOS reboot I'm not sure there's anything we can do here.
