### ISSUE TITLE
homebrew/boneyard deprecated

### ISSUE THREAD

**Issue by paolomainardi** [codekitchen/dinghy#239]
As you can see here: https://github.com/Homebrew/homebrew-boneyard/commit/98b68c6b34a8d55caffd418c4940b397a60178ce#diff-5edc0f87a41e5dd94c92e772e2ad288c

This means that unfs3 is not more available as a dependency, which makes the installation totally broken.

**Comment by codekitchen** [comment]
Oh fun, my original plan was to add unfs3 to the [Dinghy tap](https://github.com/codekitchen/homebrew-dinghy) but that never happened, guess it's time to do that.

**Comment by codekitchen** [comment]
OK it's added to the tap and everything seems to install properly -- can somebody else please try it and verify it works for them?

**Comment by m4rky77** [comment]
It's working now

**Comment by paolomainardi** [comment]
Which tap are you using for the tests ?

**Comment by m4rky77** [comment]
I use

$ brew tap codekitchen/dinghy
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (codekitchen/dinghy).
==> New Formulae
codekitchen/dinghy/unfs3

**Comment by codekitchen** [comment]
Sweet, thanks. Closing this as fixed.
