### ISSUE TITLE
Bash command/function to proxy to all docker ports on dinghy from host

### ISSUE THREAD

**Issue by herophuong** [codekitchen/dinghy#244]
Hopefully this can make it to FAQ as an alternate solution for `my-proxy`.

### 1. Requirements: [stone](http://www.gcd.org/sengoku/stone/)

```bash 
brew install stone
```

### 2. Running:

+ Directly:
       
    ```bash 
    stone `docker ps -q | grep -v $(docker ps -q --filter='name=dinghy_http_proxy') | xargs -L 1 docker port | grep -o "[0-9]\+$" | tr '\n' ' ' | sed -e "s/\([0-9]\{1,\}\)/$(dinghy ip):\1 \1 --/g"`
    ```

+ As a bash function:

    ```bash
    function dinghy-expose {
        binds=`docker ps -q | grep -v $(docker ps -q --filter='name=dinghy_http_proxy') | xargs -L 1 docker port | grep -o "[0-9]\+$" | tr '\n' ' ' | sed -e "s/\([0-9]\{1,\}\)/$(dinghy ip):\1 \1 --/g"`
        eval stone $binds
    }
    ```

### 3. Explanation:

The command will try to list all exposed ports from docker (except the ones from dinghy):
    
```bash
docker ps -q | grep -v $(docker ps -q --filter='name=dinghy_http_proxy') | xargs -L 1 docker port | grep -o "[0-9]\+$"
# Example result:
# 3000
# 4000
```

Then it will convert them to stone arguments with current dinghy ip:
    
```bash
| tr '\n' ' ' | sed -e "s/\([0-9]\{1,\}\)/$(dinghy ip):\1 \1 --/g"
# Example result:
# 192.168.99.100:3000 3000 -- 192.168.99.100:4000 4000 --
```

Then stone will create a proxy for all of the host ports to corresponding ones on dinghy:
   
```bash
stone 192.168.99.100:3000 3000 -- 192.168.99.100:4000 4000 --
```

**Comment by codekitchen** [comment]
Cool that seems reasonable, thanks for the write-up. Do you want to add it to the FAQ? Or I can probably do it later this week.

**Comment by herophuong** [comment]
I have made a pull request #245. What is your thought about having this as one of dinghy command, so user can just run, e.g `dinghy expose` to have all their ports available from localhost?

**Comment by codekitchen** [comment]
Cool thanks. A `dinghy expose` command sounds good. Since the stone command doesn't start proxying new containers when they spin up, we'd want to display a message or come up with some auto-reload scheme or something I think.

**Comment by codekitchen** [comment]
Closing as the original issue was solved, please open a separate issue/PR if you start working on a `dinghy expose` type command.
