### ISSUE TITLE
Lets Encrypt Support

### ISSUE THREAD

**Issue by ThePixelDeveloper** [codekitchen/dinghy#246]
This is more of a feature request than an issue, but it'd be cool to be able to integrate this into dinghy https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion or at least have it possible for someone to use it. Means we avoid generating and issuing self-signed certificates and the issues that come with that.

I'll submit a PR later this week if I have time.

**Comment by codekitchen** [comment]
Hm is there a way to make this work? My experience with letsencrypt has always been that the domains need to be publicly reachable over the Internet during the verification step, while Dinghy is only accessible locally.

**Comment by ThePixelDeveloper** [comment]
You're right. I didn't know the domains had to be publicly accessible. Well that's a bummer.

> The LETSENCRYPT_HOST variable most likely needs to be the same as the VIRTUAL_HOST variable and must be publicly reachable domains. Specify multiple hosts with a comma delimiter.

Was hoping I was onto a winner

**Comment by codekitchen** [comment]
Yeah, that would be sweet if it worked.
