### ISSUE TITLE
Unable to find image 'codekitchen/dinghy-http-proxy:2.5' locally

### ISSUE THREAD

**Issue by alitain** [codekitchen/dinghy#247]
When I run `dinghy create --provider parallels`, I got the message:
```
setting up DNS resolution, this will require sudo
Unable to find image 'codekitchen/dinghy-http-proxy:2.5' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 0.0.59.43:443: connect: invalid argument.
See 'docker run --help'.
   VM: running
  NFS: running
 FSEV: running
  DNS: stopped
PROXY: stopped
```

I have read the resolutions on git issues，but I did't fix the problem. I have tired with virtualbox and got the same error. My Mac OS version is 10.12.5.

**Comment by tianlai0910** [comment]
Sorry,my local dns get sth error. I have figured it out.

**Comment by alitain** [comment]
Sorry,my local dns got sth error.I have figured it out.
