### ISSUE TITLE
Unable to find image 'jwilder/nginx-proxy:latest'

### ISSUE THREAD

**Issue by codeguy** [codekitchen/dinghy#25]
Followed install instructions on OS X 10.10. When I run `dinghy up` for first time, I get this error:

    Unable to find image 'jwilder/nginx-proxy:latest' locally
    Pulling repository jwilder/nginx-proxy
    time="2015-06-03T19:03:44Z" level=fatal msg="Get https://registry-1.docker.io/v1/repositories/jwilder/nginx-proxy/tags: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: too many redirects"
    /usr/local/Cellar/dinghy/3.0.0/cli/dinghy/vagrant.rb:40:in `ssh': Error executing command: docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock --name dinghy_http_proxy jwilder/nginx-proxy (RuntimeError)
        from /usr/local/Cellar/dinghy/3.0.0/cli/dinghy/http_proxy.rb:14:in `up'
        from /usr/local/Cellar/dinghy/3.0.0/cli/cli.rb:40:in `up'
        from /usr/local/Cellar/dinghy/3.0.0/cli/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/Cellar/dinghy/3.0.0/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/Cellar/dinghy/3.0.0/cli/thor/lib/thor.rb:359:in `dispatch'
        from /usr/local/Cellar/dinghy/3.0.0/cli/thor/lib/thor/base.rb:440:in `start'
        from /usr/local/bin/dinghy:5:in `<main>'

**Comment by codekitchen** [comment]
Hi @codeguy are you still seeing this error? It seems likely to be a network problem. If the issue persists, try restarting virtualbox/vmware.

**Comment by codeguy** [comment]
I haven't had time to check. If others can't duplicate, I trust it was just a local network issue as you said. Feel free to close.

**Comment by codekitchen** [comment]
I'll close it, as I haven't seen any other reports.

**Comment by mnapoli** [comment]
Hi @codeguy :)

Got the same error today, and I got the same thing on boot2docker before too (am a new convert from boot2docker). See https://github.com/boot2docker/boot2docker/issues/451

With boot2docker I used the workaround shown here http://stackoverflow.com/questions/24060099/docker-failed-to-pull-images-from-registry which is basically use another DNS server (Google's DNS server):

```
$ boot2docker ssh
$ sudo echo "nameserver 8.8.8.8" > /etc/resolv.conf
$ sudo /etc/init.d/docker restart
```

**Comment by codeguy** [comment]
@mnapoli Small world :) Thanks! Will give that a try on my next Docker project.

**Comment by mnapoli** [comment]
Out of topic but a feedback on this project: it rocks. I can't believe I wasted days on boot2docker when this package just works (well except for this tiny issue) and is just as fast as native. I don't know why but it's faster than boot2docker + NFS…

Thanks @codekitchen!

**Comment by codekitchen** [comment]
Thanks @mnapoli 

Are you on virtualbox or vmware? I'd love to be able to repro this issue, I don't think any of my co-workers (the original audience for dinghy) have run into this specific dns failure, we're mostly on vmware.

**Comment by codeguy** [comment]
@codekitchen VirtualBox here

**Comment by mnapoli** [comment]
Virtualbox too

**Comment by dsummersl** [comment]
Had same issue - virtualbox. The google nameserver fix worked for me.
