### ISSUE TITLE
Update dinghy for multi-stage builds?

### ISSUE THREAD

**Issue by kachkaev** [codekitchen/dinghy#250]
Hi guys,

I'm using the latest dinghy 4.5.0 and my `docker version` reports 

```bash
Client:
 Version:      17.06.0-ce
 API version:  1.26 (downgraded from 1.30)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        unknown-buildtime
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5

 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I'm wondering if it's possible to upgrade dinghy to the latest docker so that [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) became possible. At the moment dinghy does not allow for something like

```bash
FROM composer:1.4 AS composer

COPY composer.json composer.lock /app/
COPY app/AppCache.php app/AppKernel.php /app/app/
RUN composer install --no-scripts


FROM php:7.1-fpm-alpine

COPY --from=composer /app/vendor .
# ...
```

This trick is pretty handy as it makes the final image much smaller. It does not have to contain all the tools that generate the final assets.

**Comment by codekitchen** [comment]
Make sure you have the latest docker-machine installed, then you can run `dinghy upgrade` and that'll call `docker-machine upgrade` under the hood to update the VM to the latest version. Sometimes docker-machine doesn't do that right for various reasons, so you may have to destroy and re-create the VM instead with `dinghy destroy`/`dinghy create`.

**Comment by kachkaev** [comment]
Thanks for your hint @codekitchen! I did not think about `dinghy upgrade` at all – pretty stupid of me :–) After running this command I finally saw 

```bash
Server:
 Version:      17.06.0-ce
```

Good buy slow Docker for mac again :–)
