### ISSUE TITLE
eval writes wrong env

### ISSUE THREAD

**Issue by hezhizhen** [codekitchen/dinghy#256]
I launched dinghy, and the output of `dinghy env` is: 
```
set -gx DOCKER_HOST tcp://192.168.99.100:2376
set -gx DOCKER_CERT_PATH /Users/hezhizhen/.docker/machine/machines/dinghy
set -gx DOCKER_TLS_VERIFY 1
set -gx DOCKER_MACHINE_NAME dinghy
```
When I ran `eval (dinghy env)` (I use fish shell), the `env` is:
```
DOCKER_CERT_PATH=/Users/hezhizhen/.docker/machine/machines/dinghy
DOCKER_HOST=tcp://192.168.99.100:2376set-gxDOCKER_CERT_PATH/Users/hezhizhen/.docker/machine/machines/dinghyset-gxDOCKER_TLS_VERIFY1set-gxDOCKER_MACHINE_NAMEdinghy
DOCKER_MACHINE_NAME=dinghy
DOCKER_TLS_VERIFY=1
```

* MacOS: 10.13.1
* dinghy: 4.6.0

**Comment by codekitchen** [comment]
I've never used the Fish shell myself, the PR to support it came from somebody else. But when I run `docker-machine env dinghy --shell=fish` I see some differences in formatting:

```bash
set -gx DOCKER_TLS_VERIFY "1";
set -gx DOCKER_HOST "tcp://192.168.64.6:2376";
set -gx DOCKER_CERT_PATH "/Users/brianp/.docker/machine/machines/dinghy";
set -gx DOCKER_MACHINE_NAME "dinghy";
```

So I wonder if we need to add quotes and semicolons to the `dinghy env` output to fix this. Seems worth trying, I'll make that change.

**Comment by codekitchen** [comment]
Yeah that fixed it, I did a quick `brew install fish` and tried it out.

https://github.com/codekitchen/dinghy/commit/c8a44d3116c4a676d237186756b198768cdff8ac

You can install Dinghy's master branch using the instructions in the README to get the fix, until I cut a new release.

**Comment by hezhizhen** [comment]
I had manually written the output of `dinghy env` to `config.fish`, and thus solved the problem. When a new version is released, I will update it and try it. Thank you for your reply and solution.
