### ISSUE TITLE
dinghy timeout

### ISSUE THREAD

**Issue by hezhizhen** [codekitchen/dinghy#259]
Today I encountered a problem with dinghy. I ran `dinghy up`, and the log was stuck in mounting. I ran `docker-machine ls`, the status of it was `Timeout`. After waiting for a few minutes, I opened Virtualbox and powered it off. And then I re-launched it, and there was nothing wrong. 
What causes it and how to prevent it? Any reply will be appreciated.

* OS: MacOS 10.13.1
* dinghy: 4.6.0

**Comment by codekitchen** [comment]
I've seen Virtualbox hang like this a few times in the past, it seems to not properly initialize the virtual networking interfaces sometimes. Unfortunately this is out of our control, I don't think it's even something that could be fixed in docker-machine.

**Comment by hezhizhen** [comment]
@codekitchen Thank you for your reply. May the luck be with me all the time.
