### ISSUE TITLE
How to customize CPU and RAM?

### ISSUE THREAD

**Issue by mnapoli** [codekitchen/dinghy#26]
Hi, first thank you this project is awesome.

It seems that the vagrant VM only uses 1 CPU. I wonder how I can customize the number of CPUs and the amount of RAM the vagrant can use? Ideally I would like to customize that once and have it applied every time I restart. Is it possible?

Thanks.

**Comment by codekitchen** [comment]
Yep, if you run `dinghy help up` you'll see the relevant options `-c` and `-m`. The options will be remembered across VM restarts, though right now they are lost if you destroy and re-build the VM.

**Comment by mnapoli** [comment]
OK great thank you!
