### ISSUE TITLE
So how does this relate to vagrant_vagrantfile

### ISSUE THREAD

**Issue by joergd** [codekitchen/dinghy#27]
Ok - I think I am being incredibly stupid.

I have two Vagrantfiles - one for my Docker containers, and a parent VM with the dinghy vagrant box.

Is this all I need for "it" to work? What is "it" - is it just the DNS and Proxy and custom NFS? Is "it" the "dinghy up" command that I use in place of "vagrant up"?

Here are my two files:

The 'parent' Vagrantfile

    Vagrant.require_version ">= 1.6.0"

    Vagrant.configure("2") do |config|
      # Assign a friendly name to this host VM
      # config.vm.hostname = "docker-host"

      # Skip checking for an updated Vagrant box
      config.vm.box_check_update = false

      # Always use Vagrant's default insecure key
      config.ssh.insert_key = false

      # Spin up a "host box" for use with the Docker provider
      config.vm.box = "codekitchen/boot2docker"

      config.vm.synced_folder "../johnnymetrics", "/vagrant", type: "nfs", disabled: false
      config.vm.synced_folder "../data", "/data", type: "nfs", disabled: false

      config.vm.network "private_network", ip: "192.168.42.69"
    end

And the one for my containers:

    Vagrant.require_version ">= 1.6.0"
    ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

    Vagrant.configure("2") do |config|

      config.vm.synced_folder ".", "/vagrant", disabled: true

      # Perform one-time configuration of Docker provider to specify
      # location of Vagrantfile for host VM
      config.vm.provider "docker" do |docker|
        docker.vagrant_vagrantfile = "../vm/Vagrantfile"
      end

      config.vm.define "mongo-machine" do |machine|
        machine.vm.provider "docker" do |d|
          d.image = "mongo:3"
          d.ports = ['27017:27017']    # host:container
          # d.volumes = ["/data/mongodb:/data"]
          d.name = 'mongo'
        end
      end

      config.ssh.insert_key = false
    end

**Comment by codekitchen** [comment]
You don't need to write any Vagrantfiles to use docker with dinghy. I think you're mixing it up with Vagrant's built-in support for docker, which I find overly complex and never use. Just run `dinghy up`, it'll tell you to set the `DOCKER_` env vars if necessary, and then you can just use docker commands as normal, like `docker run`.

I'm a little confused by your "it" questions, but maybe that clears it up?

**Comment by joergd** [comment]
I see ok - so it replaces Vagrant all together? Yes - I think that clears up the "it" questions - thanks :)

So to do something similar with Vagrantfiles where I set up my various containers etc - does dinghy have a similar concept, or is this where I need to get into "compose" or fig etc?

**Comment by codekitchen** [comment]
Dinghy just helps you get docker up and running on OS X, you'll want to read up on `docker-compose` for orchestrating multiple containers (fig is just the old name for compose).
