### ISSUE TITLE
docker-machine-nfs is faster as unfs

### ISSUE THREAD

**Issue by beardcoder** [codekitchen/dinghy#273]
A Test at both methods

unfs Result with default config
time dd if=/dev/zero of=/Users/markussommer/testfile bs=16k count=128k
2147483648 bytes (2.0GB) copied, 47.382582 seconds, 43.2MB/s
real	0m 47.38s
user	0m 0.05s
sys	0m 0.90s

nativ nfs
noacl,async,noatime,actimeo=1
docker@default:~$ time dd if=/dev/zero of=/Users/markussommer/testfile bs=16k count=128k
131072+0 records in
131072+0 records out
2147483648 bytes (2.0GB) copied, 35.859131 seconds, 57.1MB/s
real	0m 35.86s
user	0m 0.09s
sys	0m 1.47s

**Comment by codekitchen** [comment]
Hi, thanks for your interest in this. This is already well known and discussed in various issues in this repo. Closing in favor of https://github.com/codekitchen/dinghy/issues/274.
