### ISSUE TITLE
mount.nfs: an incorrect mount option was specified

### ISSUE THREAD

**Issue by tomdavidson** [codekitchen/dinghy#28]
```
Toms-MBP:webtools_config tom$ dinghy up
Bringing machine 'dinghy' up with 'virtualbox' provider...
==> dinghy: Checking if box 'codekitchen/boot2docker' is up to date...
==> dinghy: VirtualBox VM is already running.
Stopping NFS daemon, this will require sudo
Password:
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/tom
mount.nfs: an incorrect mount option was specified
mount: mounting 192.168.42.1:/Users/tom on /Users/tom failed: Device or resource busy
/usr/local/Cellar/dinghy/3.0.0/cli/dinghy/vagrant.rb:40:in `ssh': Error executing command: sudo mount -t nfs 192.168.42.1:/Users/tom /Users/tom -o nfsvers=3,udp,mountport=19321,port=19321,nolock,hard,intr 
```

**Comment by codekitchen** [comment]
dang i've been spinning up and destroying a virtualbox instance in a loop trying to reproduce this, but i haven't had any luck so far. does it happy consistently for you if you `dinghy destroy -f` and then `dinghy up` again?

also can you `dinghy ssh` into the VM and then run that mount command manually? `sudo mount -t nfs 192.168.42.1:/Users/tom /Users/tom -o nfsvers=3,udp,mountport=19321,port=19321,nolock,hard,intr`. I'm wondering if this is a race condition between spinning up the NFS server and running the mount command.

**Comment by tomdavidson** [comment]
Thanks for the quick reply. I have removed it all and tried again - and am not reproducing it either.

**Comment by codekitchen** [comment]
Darn, it probably is a race condition then. I hate just throwing in random sleeps though, so I'll wait to see if it crops up again.

**Comment by MrMMorris** [comment]
@codekitchen I hit this too sometimes. It might be when the VM is running and my macbook goes to sleep.

**Comment by lzhang** [comment]
If the mount already exists, the command will fail. To reproduce, try this sequence of commands:

```bash
$ dinghy halt
$ dinghy up
$ dinghy up
```

**Comment by lzhang** [comment]
https://github.com/codekitchen/dinghy/blob/latest/cli/dinghy/vagrant.rb#L59

We could account for this by always unmounting, then remounting, or mounting only if the mount doesn't already exist.

http://serverfault.com/questions/50585/whats-the-best-way-to-check-if-a-volume-is-mounted-in-a-bash-script

**Comment by webmonarch** [comment]
just ran into this myself.  halt && up resolved it.

**Comment by codekitchen** [comment]
Yeah I see now that the original reporter also logged `VirtualBox VM is already running`

We should add in a check to see if it's already mounted.

**Comment by codekitchen** [comment]
The latest release of dinghy properly guards against running `up` when the VM and NFS mount are already up.
