### ISSUE TITLE
408 response on docker

### ISSUE THREAD

**Issue by charlesdg** [codekitchen/dinghy#288]
I'm facing this issue with `dinghy start` since yesterday:

```
docker: Error response from daemon: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n".
```

Complete trace:

```
Password:
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/charlesdegroote
Starting the FsEvents daemon
Starting DNS and HTTP proxy
Unable to find image 'codekitchen/dinghy-http-proxy:2.5' locally
docker: Error response from daemon: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n".
See 'docker run --help'.
   VM: running
  NFS: stopped
 FSEV: stopped
  DNS: stopped
PROXY: stopped
```

Seems linked to docker. but no idea where to look for. Any clue ?

**Comment by codekitchen** [comment]
Hmm that's very strange, it looks like running `docker pull codekitchen/dinghy-http-proxy:2.5` is sending an incomplete API request to the docker registry, somehow. Does it do the same thing when you run that pull command manually? How about when pulling other images? This seems unlikely to be anything dinghy-related, I'm not sure where to start looking though. Maybe a network or proxy issue?

**Comment by charlesdg** [comment]
I fixed it using `virtualbox` in place of `xhyve`

**Comment by codekitchen** [comment]
OK, I'm going to close this then since I don't have any way to debug on my end.
