### ISSUE TITLE
Vagrant tooling integration

### ISSUE THREAD

**Issue by joergd** [codekitchen/dinghy#29]
Hey there - in your readme you say the following:

    Dinghy is built on top of Vagrant, which makes Dinghy itself simpler and if you already use Vagrant, allows __integration with all of your current Vagrant tooling__.

Does this mean something other than that dinghy uses vagrant in the background to spin up a VM? If so - what other integrations are there? Still trying to fully get my head around it. This is a really great product!

**Comment by codekitchen** [comment]
For instance, I use https://github.com/BipSync/VagrantBar to manage my Vagrant VMs. To be honest I haven't fully explored the possibility space here, since I find myself not using Vagrant for anything else these days. If you find anything else useful I'd be happy to add it to the README.

**Comment by codekitchen** [comment]
I'm going to close this issue, since dinghy no longer uses Vagrant on the back-end, but docker-machine instead.
