### ISSUE TITLE
How to access to same host and port as specified?

### ISSUE THREAD

**Issue by dalisoft** [codekitchen/dinghy#291]
Hi @codekitchen.

I tried to get your tool working and it's works good except one issue!

First of thanks for this tool and it's has great performance, when disabling all config except VM, performance 4-x faster than Docker Desktop for Mac. This tool has very good performance (not as Linux, but only just 3.5x slower than Linux, not 10-12x, like Docker Desktop for Mac).

When i run my docker image with `docker run -p 3000:3000 IMAGE_NAME`, i should able to use port `localhost:3000` from browser, but i'm cant. **But available from DOCKER_IP:3000**

Even i tried this `docker run -h localhost:localhost -p 3000:3000 IMAGE`, not available from localhost:3000.

If i enable DNS config from Dinghy preferences, i able to use `IMAGE_NAME.docker` from browser, but i need functioning this like Docker Desktop from Mac.

Used tool: `docker, docker-machine, docker-compose, xhyve + docker-machine-driver-xhyve, dinghy`

OS: macOS 10.15.1

Thanks you again for best tool!

**Comment by codekitchen** [comment]
Thanks. Dinghy does not forward ports from the VM to the host machine, so this isn't supported. It could theoretically be added using a mechanism similar to what Docker for Mac does, but it's not something I'm planning to work on myself.

**Comment by dalisoft** [comment]
Thanks, then currently my workaround is adding host like this `DOCKER_IP docker.host`!

**Comment by dalisoft** [comment]
Performance is very very great, preference editing well, clean and easy. I sure this project will get new users more than Docker Desktop over time.

**Comment by codekitchen** [comment]
ha, that's very kind of you but honestly I've been trying to deprecate this project for years. I push people to just use Docker Desktop when possible. :)  I'm sure their performance will continue to improve with time.

**Comment by dalisoft** [comment]
When i reported [issue](https://github.com/docker/for-mac/issues/3711), they even didn't answered.
Horrible performance and bad optimized things, what their product works good only CLI (not always through) and your tool solves my problem, here i can show you how i able to save 2-3GB ram and improved performance by 20-25% on macOS Catalina.

Docker for Desktop:
- Takes almost 20 second to startup on my machine
- Can't configure less than 1GB ram
- Docker for Desktop uses 300-500Mb ram + Uses almost 2GB hyperkit
- Cant select driver
- Limitation for macOS High Sierra (min OS)

Your tool:
- Maximum 7-8 second, in most cases 3-4 seconds
- Configuration is easy and able to configure use 512Mb RAM
- Maximum ram usage is 800Mb. Only 800Mb
- Able to use driver
- Can be used on all macOS (i think it's possible)

Don't forget, not all developers can get powerful machine. Our task (i also developer) make it's possible for all users and you is one of people which helps users get latest and performant Docker with your tools FREE! We not required to change computer to powerful to use Docker (we - users of this tool).

I think you understand what i mean.

Thanks again for tool.

Sorry for bad english
