### ISSUE TITLE
Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.38

### ISSUE THREAD

**Issue by mediaessenz** [codekitchen/dinghy#292]
After updating my local docker to the latest version (19.0.3.9) using `brew update && brew upgrade`, I get this error when entering  e.g. `docker ps` in the console:
```
Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.38
```

Because of the still open issue #290 I'm using the v18.06.1-ce boot2docker iso image for my parallels vm.

Now, I'm in a dead end :-(

The only way to get out of it is:
```
brew unlink docker
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/8a947170e0ebffed2e4369e1fb9c9c31a81d2f30/Formula/docker.rb
```
This installs docker 19.03.06 again, where this problem doesn't exists.

To avoid future automatic updates this could also be helpful:
```
brew pin docker
```

**Comment by codekitchen** [comment]
I'm not sure how #230 could be related, did you mean to link to a different issue?

**Comment by mediaessenz** [comment]
I meant #290. Already fixed it in my issue description.

**Comment by mediaessenz** [comment]
Meanwhile I updated to the newest docker version coming with brew (19.03.11) and the problem was solved.

So, I think this issue could be closed.

**Comment by codekitchen** [comment]
ah cool, good to hear
