### ISSUE TITLE
Upgrading docker and docker-compose

### ISSUE THREAD

**Issue by joergd** [codekitchen/dinghy#30]
Hey there - I got docker (and docker-compose) via your brew install for dinghy. Both docker and docker-compose have recently seen new releases ... What is the recommended way for me to upgrade these to the higher versions?

**Comment by codekitchen** [comment]
You can update both clients with normal homebrew commands.

For the docker server, I updated dinghy's master branch to docker 1.7 yesterday. But it's easiest to just wait for the next dinghy release, unless you have a pressing need for docker 1.7.

**Comment by tomdavidson** [comment]
Docker client and docker service need to be the same version. I suggest not upgrading the client without dingy to avoid:
```
Toms-MBP:webtools_config tom$ docker exec webtoolsconfig_web_1 bash
Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)
```

**Comment by codekitchen** [comment]
Ah yeah, thanks for pointing that out, I should've said you can upgrade `docker-compose` that way specifically.

Unfortunately, homebrew doesn't give me a way to specify which version of docker a given version of dinghy depends on, it's one of the reasons I've been contemplating moving dinghy off of homebrew. It's a great system, just maybe not a great fit here.

**Comment by codekitchen** [comment]
The 4.0.0 release of dinghy switches from vagrant to docker-machine. This should prevent any further issues with the client getting updated and a new version of the VM not being available yet.
