### ISSUE TITLE
Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)

### ISSUE THREAD

**Issue by hanskoff** [codekitchen/dinghy#33]
hi,

I've installed dinghy and wanted to call `docker ps` and see above error, any idea how to fix it?

**Comment by codekitchen** [comment]
I just released dinghy v3.0.1, which uses docker 1.7.0.  You can follow the upgrading steps @ https://github.com/codekitchen/dinghy#upgrading and that should resolve the error.

(sadly, homebrew doesn't give me a way to specify which version of the docker client dinghy depends on, so when a new version is released the docker client and server versions can get out of sync)

**Comment by hanskoff** [comment]
works fine, thnx ;)
