### ISSUE TITLE
downgrading docker version

### ISSUE THREAD

**Issue by MrMMorris** [codekitchen/dinghy#34]
Docker 1.7.0 is very much broken https://github.com/docker/docker/issues/14057

How would I go about downgrading docker in the VM?

**Comment by MrMMorris** [comment]
even with the workaround for that issue of manually `docker pull`ing the image, I run into `failed to build: Get https://index.docker.io/v1/repositories/commonsense/csm-dockerfiles/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects`

**Comment by codekitchen** [comment]
Yeah I just ran into that yesterday as well, so sad. You can install an older version of dinghy with `brew reinstall https://raw.githubusercontent.com/codekitchen/dinghy/v3.0.0/dinghy.rb`, but you'll need to convince homebrew to install an older version of the docker client as well, which is a pain.

**Comment by MrMMorris** [comment]
cool, I will try that, thanks. Definitely a sad state lately for Docker. Seems like they care more about implementing "everything and the kitchen sink" instead of making things stable...

**Comment by digitalkaoz** [comment]
@codekitchen http://stackoverflow.com/a/31145741 thats a possible solution to integrate into the dinghy vm

**Comment by digitalkaoz** [comment]
@codekitchen it works

**Comment by codekitchen** [comment]
I don't follow, how would that fix this docker 1.7 bug?

**Comment by digitalkaoz** [comment]
IT fixes the TCP to many redirects stuff which happens only with docker
vagrant systems

Brian Palmer <notifications@github.com> schrieb am Do., 9. Juli 2015 16:52:

**Comment by codekitchen** [comment]
Oh I see, this ticket got conflated with two different issues. Please open a separate ticket for the redirects issue.

I should point out though that this is how dinghy used to configure virtualbox, but it was changed because  it caused other issues with the DNS resolver. See this commit: https://github.com/codekitchen/dinghy/commit/babbfe7f81ae43226298d410c271d97bef71adac

I think the final solution will be to change dinghy's `*.docker` DNS resolver to not rely on the OS X host's `/etc/resolver` functionality, and instead modify the VM's iptables directly, similar to how https://github.com/phinze/landrush does it. It might be a while before I can tackle that though.

**Comment by MrMMorris** [comment]
@codekitchen when can we expect 1.7.1? I have a habit of pointing people with b2d problems in IRC to your lovely alternative, but I am reluctant as 1.7.0 is completely broken.

**Comment by codekitchen** [comment]
I released it on the 15th -- see https://github.com/codekitchen/dinghy/blob/latest/CHANGELOG.md#302---2015-07-15

You'll need to upgrade dinghy and the VM following the instructions in the README https://github.com/codekitchen/dinghy#upgrading

**Comment by MrMMorris** [comment]
ah, I did `dinghy upgrade` without upgrading Dinghy itself. Thanks!

**Comment by codekitchen** [comment]
oh hm I can see how that'd be confusing. maybe `dinghy upgrade` should ping github to see if there's a newer version of dinghy itself available.

**Comment by MrMMorris** [comment]
@codekitchen I think a more pressing need would be the ability to choose what version of docker to run if possible :bowtie:

**Comment by MrMMorris** [comment]
@codekitchen I really need a way of installing an older version of `docker`. One of the developers accidentally upgraded to 1.10 and I don't want to be using the latest as I know the network stack rewrite they did will introduce all sorts of issues.

**Comment by codekitchen** [comment]
Hey @MrMMorris now that dinghy runs on top of docker-machine and doesn't manage installing docker itself, there's nothing in dinghy anymore blocking you from changing server and client versions yourself. I haven't tried it myself though, so I don't know exactly what commands you'd want to run -- maybe docker-machine has it documented somewhere?

**Comment by MrMMorris** [comment]
@codekitchen wow you are fast at responding :smile: 

I will take a look, thanks!

**Comment by codekitchen** [comment]
Haha, you were just fortunate enough to ask a question while I was catching up on email while walking the dog :)
