### ISSUE TITLE
MAJOR issues on Yosemite

### ISSUE THREAD

**Issue by MrMMorris** [codekitchen/dinghy#35]
I am running into freezing issues on my macbook with Yosemite 10.10.1 and dinghy 3.0.1 which seem to have started since installing dinghy. I can login, but slowly things start to break down until everything freezes and I have to reboot.

Checked the Console logs and this is what I see leading up to the freezes:

```
com.apple.xpc.launchd: (dingy.unfs[459]) Service exited with abnormal code: 1
com.apple.xpc.launchd: (dingy.unfs) Service only ran for 0 seconds. Pushing respawn out by 10 seconds
com.apple.xpc.launchd: (dingy.unfs[460]) Service exited with abnormal code: 1
com.apple.xpc.launchd: (dingy.unfs) Service only ran for 0 seconds. Pushing respawn out by 10 seconds
com.apple.xpc.launchd: (dingy.unfs[461]) Service exited with abnormal code: 1
com.apple.xpc.launchd: (dingy.unfs) Service only ran for 0 seconds. Pushing respawn out by 10 seconds
com.apple.xpc.launchd: (dingy.unfs[462]) Service exited with abnormal code: 1
com.apple.xpc.launchd: (dingy.unfs) Service only ran for 0 seconds. Pushing respawn out by 10 seconds
```

I have logged in and quickly opened a terminal to run `ps -ef | grep dinghy`. I run it until `xpcproxy dinghy.dnsmasq` comes up, but by the time I try and `kill -9 <process id>` the freezing has already started and I can't.

I checked Activity Monitor and I don't see Vbox and nothing is showing as sucking up resources.

Any ideas? Can I stop dinghy from trying to start?

My laptop is completely unusable at the moment :sob:

**Comment by codekitchen** [comment]
Odd, that's the NFS daemon, which shouldn't normally be running on its own. And I don't know how it could eat up your whole laptop, especially since launchd throttles respawning. You can try a `sudo launchctl unload /Library/LaunchDaemons/dinghy.unfs.plist` or even just deleting that file, that should stop launchd from trying to run it anymore. Running it manually with the below command might show some output about what's blowing up:

`sudo /usr/local/sbin/unfsd -e /usr/local/etc/dinghy-nfs-exports -n 19321 -m 19321 -l 192.168.42.1 -p -b -d`

**Comment by MrMMorris** [comment]
shoot, looks like I can't even delete that file before things lock up. I am awaiting a password for a local admin account on my local. I'll see if the issue is just my account.

**Comment by MrMMorris** [comment]
so I was able to log into another local account and delete the plist, but I am still seeing the dinghy.dnsmasq process and Console errors.

I can't run the unfsd command before the locking up on either account. 

I also deleted the vbox plist and that hasn't helped...

**Comment by codekitchen** [comment]
Hm you can try disabling/deleting the `$HOME/Library/LaunchAgents/dinghy.dnsmasq.plist` launchd task as well. I'll be surprised if `dnsmasq` is what's causing such severe lockups, but who knows. Maybe it's triggering some bad behavior by binding to `192.168.42.1`, which is a virtualbox virtual network interface.

**Comment by MrMMorris** [comment]
@codekitchen so after much frustration, it (luckily?) seems like it's a hardware issue :smile: Thanks for trying to help me through my craziness. I am just glad It wasn't an issue with dinghy! :fireworks:

**Comment by codekitchen** [comment]
Whew, good to hear for sure! Sorry about your laptop though. :)

**Comment by MrMMorris** [comment]
@codekitchen so I got my old laptop working again. OS corruption.

Now I am trying to get Dinghy going again and hit this error:
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg*, int, int*)" at line 66 of file VBoxManageHostonly.cpp

/usr/local/Cellar/dinghy/3.0.1/cli/dinghy/vagrant.rb:21:in `up': There was an error bringing up the Vagrant box. Dinghy cannot continue. (RuntimeError)
	from /usr/local/Cellar/dinghy/3.0.1/cli/cli.rb:33:in `up'
	from /usr/local/Cellar/dinghy/3.0.1/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/3.0.1/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/3.0.1/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/3.0.1/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/dinghy:5:in `<main>'
```

The solution seems to be `sudo /Library/StartupItems/VirtualBox/VirtualBox restart`, but I had removed all StartupItems/LaunchAgents/LaunchDaemons in the troubleshooting. I tried uninstalling vagrant and destroying dinghy and then installing again, but I still get the error.

Any idea how I can get those files back?

**Comment by MrMMorris** [comment]
looks like reinstalling VirtualBox did it :smile_cat:
