### ISSUE TITLE
nodemon doesn't seem to work properly with dinghy

### ISSUE THREAD

**Issue by 1N50MN14** [codekitchen/dinghy#37]
For some reason nodemon fails to restart node when using a docker volume, any ideas as to what might be causing this?

**Comment by therpr** [comment]
I am waiting for the fix too.

https://github.com/remy/nodemon/issues/419

**Comment by codekitchen** [comment]
Yep, the primary reason is that file shares over NFS don't support inotify filesystem events. There's an epic discussion over at https://github.com/codekitchen/dinghy/issues/9 , but the tl;dr is that you can try out my experimental solution as discussed at https://github.com/codekitchen/dinghy/issues/9#issuecomment-112856785 , I'd love to hear if it works well with nodemon. I'll close this in favor of that existing issue.
