### ISSUE TITLE
docker 1.7

### ISSUE THREAD

**Issue by digitalkaoz** [codekitchen/dinghy#38]
the boot2docker image is missing...can you create and upload this image?

**Comment by codekitchen** [comment]
I published it a couple weeks ago, you can see it at https://atlas.hashicorp.com/codekitchen/boxes/boot2docker

Did you get an error? Maybe Atlas is having issues, I know that Hashicorp just released it to "General Availability" yesterday so they're probably doing lots of deploys. Probably just try again.

**Comment by digitalkaoz** [comment]
mh ok. a `dinghy upgrade` said 1.6 is the newest and everything is fine...ill try again and close here. thanks!

**Comment by codekitchen** [comment]
Ah, OK. Just to be sure, did you do the reinstall first before running upgrade, as outlined @ https://github.com/codekitchen/dinghy#upgrading ?

**Comment by codekitchen** [comment]
Closing this, let me know if it's still an issue
