### ISSUE TITLE
Server Error: too many redirects

### ISSUE THREAD

**Issue by markoshust** [codekitchen/dinghy#39]
I believe these two issues are related.

Upon restarting dinghy (after upgrade, etc), I get this error:

$ docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock --name dinghy_http_proxy codekitchen/dinghy-http-proxy
Unable to find image 'codekitchen/dinghy-http-proxy:latest' locally
Pulling repository codekitchen/dinghy-http-proxy
FATA[0001] Get https://index.docker.io/v1/repositories/codekitchen/dinghy-http-proxy/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects 

And trying to execute a 'docker login':

$ docker login
Username: xxx
Password: 
Email: xxx
FATA[0018] Error response from daemon: Server Error: Post https://index.docker.io/v1/users/: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects 

Dinghy/Docker are both up and functional otherwise. Dinghy comes up with no errors after Mac reboot, however `docker login` always shows this same error.

**Comment by codekitchen** [comment]
I'm guessing this is using virtualbox? I think this is a fairly widespread issue, see the final couple comments here: https://github.com/codekitchen/dinghy/issues/34#issuecomment-120055553

That workaround may fix things for you, but it may break the proxy DNS support at the same time. I need to look into an alternate solution.

**Comment by codekitchen** [comment]
None of my trusty guinea pigs have seen this since switching to the new 4.0 version of dinghy that is backed by docker-machine instead of Vagrant. The networking configuration under docker-machine is much simpler, so this doesn't surprise me.

I'm going to close this, but let me know if it continues to be an issue after upgrading. Thanks!

**Comment by markoshust** [comment]
Thanks -- is the `machine` branch ok to be used yet or when the release date will be (or stable enough to use daily). Let me know if there is any changing documentation on this version and I'll test it out.

**Comment by codekitchen** [comment]
Yep, you'll mostly want to follow the normal upgrade instructions @ https://github.com/codekitchen/dinghy#upgrading , but see the caveats at https://github.com/codekitchen/dinghy/blob/latest/UPGRADE_FROM_VAGRANT.md

**Comment by markoshust** [comment]
Oh, you just released it -- awesome!! This is such perfect timing. Presenting at a tech conference in a couple weeks and I'm pushing dinghy because it's awesome -- this is perfect. Thanks mucho!

**Comment by codekitchen** [comment]
Hey that's awesome, thanks for the shout out. I'm curious, what conference?

**Comment by markoshust** [comment]
Meet Magento in NY
http://ny.meet-magento.com/
