### ISSUE TITLE
Error on Dinghy installation

### ISSUE THREAD

**Issue by stevevega** [codekitchen/dinghy#41]
I'm getting the following error when trying to install Dinghy:
> brew install https://github.com/codekitchen/dinghy/raw/latest/dinghy.rb

```
######################################################################## 100.0%
==> Installing dependencies for dinghy: unfs3, dnsmasq
==> Installing dinghy dependency: unfs3
==> Downloading https://downloads.sourceforge.net/project/unfs3/unfs3/0.9.22/unfs3-0.9.22.tar.gz
==> Downloading from http://downloads.sourceforge.net/#!/project/unfs3/unfs3/0.9.22/unfs3-0.9.22.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: a6c83e1210ce75836c672cd76e66577bfef7a17a
Actual: ea60df615387f47bdfdfe4da48f6567c4ec60f74
Archive: /Library/Caches/Homebrew/unfs3-0.9.22.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by codekitchen** [comment]
Hm, looks like sourceforge made a change that broke homebrew's downloading of the `unfs3` dependency. I just tried it and it worked though, so it was probably just a temporary problem. Try again, or try `brew install unfs3` directly to test.

**Comment by stevevega** [comment]
For me is not working for me using ```brew install unfs3``` either.

**Comment by codekitchen** [comment]
Hm have you done a `brew update` recently?

**Comment by stevevega** [comment]
I just installed brew on this machine today.

**Comment by codekitchen** [comment]
Ah yeah, if I clear out all homebrew's caches I can repro the problem. It looks like sourceforge must've made a change that breaks the unfs3 download, that's rough.

I found this just-opened issue, looks like it's affecting all homebrew formulas that download from sourceforge: https://github.com/Homebrew/homebrew/issues/41778

Not much I can do on dinghy's end, we'll have to wait for homebrew or sourceforge to resolve it.

**Comment by stevevega** [comment]
Awesome thanks!

**Comment by codekitchen** [comment]
the (awful) workaround is to download the unfs tar.gz manually using your browser (just go to  https://downloads.sourceforge.net/project/unfs3/unfs3/0.9.22/unfs3-0.9.22.tar.gz ) and copy it into `/Library/Caches/Homebrew/unfs3-0.9.22.tar.gz`

**Comment by codekitchen** [comment]
I'm going to re-open this as a reference to the workaround while upstream works on a fix

**Comment by codekitchen** [comment]
sourceforge is fixed now. you might have to clear your homebrew cache.

**Comment by chedaroo** [comment]
I think this has come back round again, just had to manually download and copy it to the cache

**Comment by justafish** [comment]
Also having the same issue and I'm unable to download from sf. This mirror worked for me: https://www.mirrorservice.org/sites/download.sourceforge.net/pub/sourceforge/u/un/unfs3/unfs3/0.9.22/unfs3-0.9.22.tar.gz

**Comment by mikewolfd** [comment]
Brew install dinghy breaks at unfs3. 

the unfs3 keg was moved to homebrew/boneyard/unfs3 a day ago.
