### ISSUE TITLE
store images/containers on the host?

### ISSUE THREAD

**Issue by codekitchen** [codekitchen/dinghy#43]
Upsides:

* You don't have to re-download base images if you destroy and re-create the VM
* You aren't limited by the VM's disk size

Downsides:

* Destroying the VM is no longer enough to clean up everything -- images will still take up space on the host
* There's likely a performance penalty

**Comment by zwily** [comment]
It looks like the layers are stored on a separate .vmdk in the boot2docker vm. It may be preferable to come up with a way to keep that around when upgrading the volume itself. (Optionally of course - there will be cases where you want to start completely fresh.)

**Comment by markoshust** [comment]
Big upvote on this. I just found out doing a `dinghy upgrade` deleted all of my custom images and containers.

If the layers are stored on a .vmdk folder, can we just remote mount this on the host?

I'm wondering if this would also be a possible alternative: doing something that works like git stash. Where you can execute a `dinghy stash` which will copy the layer data to the host. Then do a `dinghy stash apply` which will copy them back after a dinghy upgrade is complete.

**Comment by codekitchen** [comment]
I'm not sure this is worth the effort anymore, now that we're using docker-machine and upgrades don't delete images and containers. The only reason would be to preserve stuff across a VM destroy/create, which is much less common.

**Comment by codekitchen** [comment]
Gonna close this out, not worth it anymore
