### ISSUE TITLE
Client and server don't have same version

### ISSUE THREAD

**Issue by mnapoli** [codekitchen/dinghy#46]
I keep getting the following error even though I just updated everything today (both brew and `dinghy upgrade`):

> Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)

Is there something wrong with my setup? Should I wait for a new release of Dinghy?

**Comment by codekitchen** [comment]
Sounds like your VM is still running docker version 1.7.0. Does `/usr/local/var/dinghy/vagrant/Vagrantfile` show `config.vm.box_version = "1.7.1"` ?

`dinghy upgrade` essentially just does `cd /usr/local/var/dinghy/vagrant` and then runs `vagrant box update && vagrant destroy`, creating a new VM using the latest image.

**Comment by mnapoli** [comment]
Nope it contains `config.vm.box_version = "1.6.0"`

I'm not sure I understood what you meant, how should I upgrade?

**Comment by mnapoli** [comment]
Woops nevermind I just realized that there are special instructions to upgrade Dinghy (https://github.com/codekitchen/dinghy#upgrading), I was expecting it to be handled by brew ;) my mistake

Will try that! Thanks
