### ISSUE TITLE
Error: undefined method `head?' for nil:NilClass

### ISSUE THREAD

**Issue by haggen** [codekitchen/dinghy#48]
I ran `brew install https://github.com/codekitchen/dinghy/raw/latest/dinghy.rb` and got this:

```
Error: undefined method `head?' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/pkg_version.rb:16:in `initialize'
/usr/local/Library/Homebrew/formula.rb:305:in `new'
/usr/local/Library/Homebrew/formula.rb:305:in `installed_prefix'
/usr/local/Library/Homebrew/formula.rb:284:in `installed?'
/usr/local/Library/Homebrew/cmd/install.rb:72:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:127:in `<main>'
```

I'm on OS X El Capitan Beta (15A235d) and just installed Vagrant to use dinghy.

**Comment by codekitchen** [comment]
At first glance that looks like a problem with Homebrew, probably an incompatibility with El Capitan. Have you had luck installing other Homebrew formulas on the beta?

**Comment by haggen** [comment]
I had indeed:

```
☁  ~  brew list
gdbm		lua		node		pcre		pkg-config	zsh
```

**Comment by codekitchen** [comment]
I just `brew up`'d and then uninstalled and re-installed dinghy, and I hit the same error. Something must've changed in homebrew in the last few days, but since I can repro on Yosemite it won't be hard to track down.

**Comment by haggen** [comment]
Haha sorry for having you messing up your dinghy installation, and thanks for the quick response. :)

**Comment by haggen** [comment]
Maybe it's related to this commit ? https://github.com/Homebrew/homebrew/commit/8ba134eda537d2cee7daa7ebdd9f728389d9c53e

**Comment by codekitchen** [comment]
No worries. They changed how `devel` blocks download the code, breaking a hack I had in place to make installing from local dir work: https://github.com/codekitchen/dinghy/commit/41e332d6dabba39fd3f65f1118fd28fb254d04b7

Easy fix, you should be good now.

**Comment by haggen** [comment]
You're awesome! ;) Thanks a bunch!
