### ISSUE TITLE
The specified host network collides with a non-hostonly network!

### ISSUE THREAD

**Issue by jgmartin** [codekitchen/dinghy#50]
Upon a fresh install of Vagrant and Dinghy, i'm receiving the following error when attempting to `dinghy up` for the first time:

    The specified host network collides with a non-hostonly network!
    This will cause your specified IP to be inaccessible. Please change
    the IP or name of your host only network so that it no longer matches that of
    a bridged or non-hostonly network.

My local IP range is 192.168.10.x, and i've confirmed than there are no host-only networks in that range on my machine (or in the 192.168.42.x range).  

The full console output is as follows:

    Bringing machine 'dinghy' up with 'virtualbox' provider...
    ==> dinghy: Checking if box 'codekitchen/boot2docker' is up to date...
    ==> dinghy: Clearing any previously set network interfaces...
    The specified host network collides with a non-hostonly network!
    This will cause your specified IP to be inaccessible. Please change
    the IP or name of your host only network so that it no longer matches that of
    a bridged or non-hostonly network.
    /usr/local/Cellar/dinghy/3.0.4/cli/dinghy/vagrant.rb:21:in `up': There was an error bringing up the Vagrant box. Dinghy cannot continue. (RuntimeError)
	    from /usr/local/Cellar/dinghy/3.0.4/cli/cli.rb:33:in `up'
	    from /usr/local/Cellar/dinghy/3.0.4/cli/thor/lib/thor/command.rb:27:in `run'
	    from /usr/local/Cellar/dinghy/3.0.4/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	    from /usr/local/Cellar/dinghy/3.0.4/cli/thor/lib/thor.rb:359:in `dispatch'
	    from /usr/local/Cellar/dinghy/3.0.4/cli/thor/lib/thor/base.rb:440:in `start'
	    from /usr/local/bin/dinghy:5:in `<main>'

Any help in diagnosing this issue would be much appreciated.  Thanks!

**Comment by codekitchen** [comment]
Darn, I knew that using a hard-coded IP would bite somebody eventually, but I haven't gotten around to making it dynamic.

Interesting that you can't find any other networks in the `192.168.42.x` range though. Does virtualbox list any in preferences -> network?

**Comment by jgmartin** [comment]
Nope... there was one originally but it was removed (and the system restarted, etc) and the issue persisted.  It was a host-only network.

**Comment by jgmartin** [comment]
Upon further investigation, it looks like the cause of the problem lies within the codekitchen/boot2docker image.  Vagrant returns the error under all cases when trying to spin up this image, but it able to spin up other boot2docker images with the same configuration.

**Comment by codekitchen** [comment]
Oh there's another interface in the base codekitchen/boot2docker image, and sure enough it's `192.168.10.10`: https://github.com/codekitchen/boot2docker-vagrant-box/blob/master/vagrantfile.tpl#L13

I actually inherited that config from upstream: https://github.com/dduportal/boot2docker-vagrant-box/blob/master/vagrantfile.tpl#L23 I don't think it's even needed for dinghy. I'll look into just removing it.

**Comment by mlhamel** [comment]
In fact, i've got vmware fusion and got exactly the same issue. Not sure if there's something equivalent for it but still didn't found it.

**Comment by codekitchen** [comment]
OK the master branch doesn't have a `192.168.10.10` interface anymore. I'm not ready to cut a new release yet, but you can install the master branch by following these instructions: https://github.com/codekitchen/dinghy#prereleases

`192.168.42.10` is still hard-coded, so if you have a conflict there this won't help.

**Comment by mlhamel** [comment]
It do work like a charm, that's amazing, and the next release should fix this issue completely. Thanks !

**Comment by codekitchen** [comment]
ok, this has been released. i'll track a separate issue for making the 192.168.42.1 interface dynamic.

**Comment by assadali007** [comment]
The specified host network collides with a non-hostonly network!
This will cause your specified IP to be inaccessible. Please change
the IP or name of your host only network so that it no longer matches that of
a bridged or non-hostonly network.

Bridged Network Address: '192.168.10.0'
Host-only Network 'en0: Wi-Fi (AirPort)': '192.168.10.0'

**Comment by assadali007** [comment]
i have a same issue please could you help me how what do to solve the problem
