### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by MrMMorris** [codekitchen/dinghy#54]
Moved to latest version to try out `fsevents_to_vm`. Ran into this:

`An error occurred trying to connect: Get https://127.0.0.1:2376/v1.19/containers/json: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "serial:264826990604929301496151133139566451714")`

Someone mentioned it might be because of installation through Homebrew

https://github.com/boot2docker/boot2docker/issues/803

Any ideas?

**Comment by codekitchen** [comment]
Hm you could download the pre-built docker binary from https://docs.docker.com/installation/binaries/#get-the-mac-os-x-binary and try with that, to determine if it's a problem with the homebrew-built docker client binary or not.

**Comment by MrMMorris** [comment]
figured it out! I saw that on virtualbox there were 2 dinghy vms so I removed both and reinstalled dinghy
