### ISSUE TITLE
client/server version mismatches are common

### ISSUE THREAD

**Issue by codekitchen** [codekitchen/dinghy#55]
Since dinghy relies on homebrew to install the docker client on the host, and since homebrew doesn't allow you to specify what version of a dependency is required, it's common for the docker client to be incompatible with the server version running in the VM.

First step is for dinghy to detect this and show some useful information, but we might have to go outside of homebrew to install the docker client to fully fix it. Or maybe it's sufficient for dinghy to tell the user to run `brew switch`.

**Comment by codekitchen** [comment]
you can't `brew switch` if the version isn't already installed, and `brew versions` is no longer a thing, so you'd have to find the right version from the history https://github.com/Homebrew/homebrew/commits/master/Library/Formula/docker.rb and brew install https://raw.githubusercontent.com/Homebrew/homebrew/e0ee620afd7ecbd53f645c3de87bab9723314a3b/Library/Formula/docker.rb etc

**Comment by haggen** [comment]
Why don't you update dinghy to use the new API version (currently 1.20) ?

**Comment by codekitchen** [comment]
yes, it takes about 15 minutes, i plan to do that as soon as i can. but this ticket is about the more general issue, it's impossible for dinghy to always be released in lock-step with docker being updated in homebrew.

**Comment by haggen** [comment]
Oh sure, I understand that. :) My questions was more of a informational one, I sniffed the code and wanted to know if I got it right.

Do I make your life easier if I send a pull request for that ?

**Comment by codekitchen** [comment]
Nah, I appreciate it but it's mostly automated, I just have to bump the version. I can't build the new image until I'm back where I have good Internet though, on my phone right now. :)

**Comment by haggen** [comment]
Would it work if a script hooked to the releases of boot2dockcer/boot2docker repo did that ? Or is there a manual verification (like seeing log messages) if things are working correctly, and no breaking change was made ?

**Comment by chrisgeo** [comment]
@codekitchen I've been stuck waiting for dinghy to also update to the latest VirtualBox guest additions - so make there might be a way to try those with boot2docker to automate the process? Or best case - can we tell dinghy to use a local version of a built box?

**Comment by codekitchen** [comment]
ok, this has been released. @chrisgeo for future reference, you could modify `/usr/local/var/dinghy/vagrant/Vagrantfile` to point at a locally-built box, but be aware that the file will be overwritten the next time you update dinghy.

boot2docker sometimes makes a change that requires changing the packer/vagrant build, fully automating the update would be difficult. The eventual solution is https://github.com/codekitchen/dinghy/issues/16 , since once dinghy is running on top of docker-machine instead of vagrant, there will be no need to build our own images and versions will stay in sync via homebrew. I don't have a timeline for that yet, but hopefully soon.

**Comment by codekitchen** [comment]
I'm punting on this as it looks like using docker-machine isn't far off, see https://github.com/codekitchen/dinghy/issues/16#issuecomment-131892521
