### ISSUE TITLE
Local DNS not propagating into docker container

### ISSUE THREAD

**Issue by egyptianbman** [codekitchen/dinghy#60]
Hello,

I'm on the machine branch and wow is it faster!!!  I apologize if you don't want people creating issues for the machine branch because I know it's still in heavy development but I wanted to let you know that I have two containers who are not linked but communicate with each other via the local `*.docker` dns.

I'm finding that in the new branch, the two containers aren't accessing the local DNS.  For the time being I'm just `echo "192.168.99.100 other-container-vhost.docker" >> /etc/hosts` and updating it whenever the ip changes which luckily isn't often.

I've also noticed that FSEV is not running but I saw a commit around four hours ago about that so I think that's new.

Thank you, keep up the good work and let me know if you need me to try anything or provide more information, thanks!

**Comment by codekitchen** [comment]
Good catch, thanks, I hadn't tested that yet.

Let me know if FSEV continues to not work for you, it should be working now.

**Comment by codekitchen** [comment]
looks like this affects virtualbox but not vmware.

i don't have as much control over network configuration as i did with vagrant, so the only option might be to run a DNS proxy and point the VM to use that.

**Comment by codekitchen** [comment]
Oh good, actually the same fix that worked under Vagrant works here, setting `natdnshostresolver1` on the virtualbox vm.

**Comment by egyptianbman** [comment]
Thank you!
