### ISSUE TITLE
Ability to customize sharing root directory

### ISSUE THREAD

**Issue by bentruyman** [codekitchen/dinghy#7]
For reasons I won't go into here, source code on my machine doesn't live beneath `$HOME`, but rather `/src`. It would be nice to customize this.

**Comment by codekitchen** [comment]
That's reasonable. I recently added a preferences file https://github.com/codekitchen/dinghy/blob/latest/cli/dinghy/preferences.rb , it could be stored there and added as an option to the `dinghy up` CLI command.

**Comment by codekitchen** [comment]
There was a PR merged for this a while back, https://github.com/codekitchen/dinghy/pull/45

I'd like to see it in the preferences file still, rather than just as ENV vars, but the functionality is there.
