### ISSUE TITLE
Make docker/docker-machine brew install optional?

### ISSUE THREAD

**Issue by jgeiger** [codekitchen/dinghy#70]
I've already got docker and docker-machine installed from the toolbox and I don't need to have brew install them.

I was able to create a fork that removed the dependency, but I think it's a bit more complicated than that for the general use case due to installed version numbers and matching the installed boot2docker.iso version.

**Comment by codekitchen** [comment]
I agree it would be nice to support both homebrew and toolbox for installing these deps. I'm not sure how to do that yet without making it more of a hassle. I still need to find some time to try out toolbox, I've never used it.

**Comment by jgeiger** [comment]
All I did was remove the dependency from the install script. Everything "seemed" to work for me, but I was also already on docker 1.8.2 from the toolbox.

> docker-machine ls 
showed both machines, and I added a command to set the dinghy machine active and that worked as well.

dmu() {
  eval "$(docker-machine env $1)"
}
> dmu dinghy

By default my .zshrc evals the dev default docker-machine. So I need to do the switch every time I open a new terminal, but it was just for testing anyway.

**Comment by ericclemmons** [comment]
Found this as I was trying out `rocker-machine`.  Anyway, Docker Toolbox is the recommended way to go, so I think what makes the most sense is to do a major version release where the README indicates that Docker Toolbox should be installed _first_, then installing this binary.

**Comment by codekitchen** [comment]
Despite what the docker company recommends, I much prefer using homebrew, and most of my co-workers do as well. So I'd want an implementation that works well for both.

**Comment by Kallin** [comment]
:+1: I also ended up forking just to remove the docker brew dependency. Seems like Docker is going all in with this kitematic distribution so probably a number of people will be coming at this from that angle.

**Comment by codekitchen** [comment]
I think the ideal solution would be to remove the hardcoded dependencies from the homebrew recipe. Then have dinghy look for docker and machine, and if they aren't installed (or wrong versions), give the user the homebrew command to install them, and a link to Kitematic, and they can choose what to do.

I probably won't have time to do that in the next couple weeks though. I'd much appreciate a PR from somebody with experience using Kitematic if anybody is interested.

**Comment by Kallin** [comment]
created a PR removing brew dependencies on docker/docker-machine and referring users to docker-toolbox/brew to go get 'em when you try to start dinghy if they're missing.

**Comment by codekitchen** [comment]
This is in the latest release, thanks again
