### ISSUE TITLE
Check if system nfsd is running and provide instructions to disable

### ISSUE THREAD

**Issue by ilkka** [codekitchen/dinghy#72]
It seems unfsd silently fails to start during `dinghy create` if the system nfsd is enabled. It'd be cool if dinghy could check this and instruct the user to run `sudo nfsd disable`.

**Comment by codekitchen** [comment]
I can't reproduce this, I've always used dinghy with system `nfsd` running as well, for some Vagrant VMs that I have to keep around for now. Do you have more details on what you're seeing?

**Comment by ilkka** [comment]
Yeah, there might have been something else weird happening with my machine, because even after nfsd was dead, dead, dead, unfsd complained that port 19321 was in use, but `lsof` didn't report anything there.
