### ISSUE TITLE
Seeing 'FSEV: not running' on dinghy 4.0.2

### ISSUE THREAD

**Issue by aisipos** [codekitchen/dinghy#73]
I can't seem to get fsevents to work on my machine (OS X 10.10.5)

After running, dinghy up, I always see:
```
> dinghy status
  VM: running
 NFS: running
FSEV: not running
 DNS: running
HTTP: running
```

Checking manually on the fsevents daemon:
```
> ps -ef | grep -i fsev                                                                                                                                                                                                      master [7027548]
    0    47     1   0  2Sep15 ??        10:20.95 /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/Support/fseventsd
  501 41998     1   0 11:46AM ??         0:00.25 fsevents_to_vm
  501 42009 41998   0 11:46AM ??         0:00.01 /Library/Ruby/Gems/2.0.0/gems/rb-fsevent-0.9.5/bin/fsevent_watch --file-events /Users/anton
    0 42102 39290   0 11:46AM ??         0:00.17 /Library/DropboxHelperTools/Dropbox_u501/dbfseventsd
    0 42103 42102   0 11:46AM ??         0:00.47 /Library/DropboxHelperTools/Dropbox_u501/dbfseventsd
  501 42104 42103   0 11:46AM ??         0:00.36 /Library/DropboxHelperTools/Dropbox_u501/dbfseventsd
  501 42158 14285   0 11:47AM ttys015    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -i fsev
```

So I see a fsevent_watch process, but no fsevents_to_vm process

If I manually run:

```
launchctl unload -w /Users/anton/Library/LaunchAgents/dinghy.fsevents_to_vm.plist
launchctl load -w /Users/anton/Library/LaunchAgents/dinghy.fsevents_to_vm.plist
```

I see no errors printed to the terminal. There are some related messages in my logs though:
```
9/17/15 11:46:31.483 AM com.apple.xpc.launchd[1]: (dinghy.fsevents_to_vm) This service is defined to be constantly running and is inherently inefficient.
9/17/15 11:46:33.000 AM kernel[0]: fsevents: watcher dbfseventsd (pid: 42010) - Using /dev/fsevents directly is unsupported.  Migrate to FSEventsFramework
```
I can't tell though if these are 'fatal'.

Any thoughts on how to further diagnose the issue? If it helps, here's some more info:
```>
 head -n 1 `which fsevents_to_vm`                                                                                                                                                                                           
#!/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
```

```
> mdfind fsevents_to_vm | grep -i fsevents_to_vm
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/fsevents_to_vm.rb
/Users/anton/Library/LaunchAgents/dinghy.fsevents_to_vm.plist
/Library/Ruby/Gems/2.0.0/cache/fsevents_to_vm-1.0.1.gem
/Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.0.1
/Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.0.1/exe/fsevents_to_vm
/Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.0.1/fsevents_to_vm.gemspec
/Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.0.1/lib/fsevents_to_vm.rb
/Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.0.1/lib/fsevents_to_vm
/usr/bin/fsevents_to_vm
/Library/Ruby/Gems/2.0.0/specifications/fsevents_to_vm-1.0.1.gemspec
/Users/anton/code/dinghy/cli/dinghy/fsevents_to_vm.rb
```
My preferences.yml:
```
---
:preferences:
  :proxy_disabled: false
  :fsevents_disabled: false
  :create:
    provider: virtualbox
```

**Comment by codekitchen** [comment]
hm, it looks to me like it is in your `ps` output, pid `41998`. am I missing something? it does seem like something is wrong though, if `dinghy status` reports it not running.

those log messages are ok. what happens if you run it manually? try `/usr/bin/fsevents_to_vm start --debug` with dinghy up and running. if it doesn't exit immediately, try modifying a couple files in your home dir, it should print out the events when you specify `--debug`.

**Comment by aisipos** [comment]
Hmmm- 2 things:

It seems if you have `brew install proctools` installed, pgrep won't find fsevents_to_vm:

```
> type pgrep                                                                                                                                                                                                                 
pgrep is /usr/local/bin/pgrep

> /usr/bin/pgrep fsevents_to_vm                                                                                                                                                                                              49517

anton@proliner:~/code/dinghy
> /usr/local/bin/pgrep fsevents_to_vm

```
(The last output is empty). If I `brew uninstall proctools`, now dinghy status is working:

```
> dinghy status 
  VM: running
 NFS: running
FSEV: running
 DNS: running
HTTP: running
```

Now, even though fsevents is running, I'm not sure the container is seeing my events. I'm running nodemon in the container on a node.js app (nodemon watches a directory and restarts the node app if files change). If I change files on my host, I don't see nodemon restart the app, but if I `cat` the file I changed on the host from inside the container I do see the changes I made. So it seems fsevents aren't getting forwarded to the container for me. Any thoughts on how to debug that? I tried your experiment above with the debug flag, and I do see a console output that at least on the host it is seeing fs events.

**Comment by codekitchen** [comment]
Ah, I should've known that my lazy pgrep would be problematic, filed https://github.com/codekitchen/dinghy/issues/74 for that

**Comment by aisipos** [comment]
Any thoughts on how to debug fsevents not being seen in the container? (and realizing that is reallly a separate issue) Thanks for all your help!

**Comment by codekitchen** [comment]
I should probably write a "troubleshooting fsevents" doc as this has come up a few times. If you see the events when running in the foreground with `--debug`, and it doesn't print out any errors, it's likely that events are making it to VM. I'm not familiar with nodemon, but does it use inotify by default, or do you need to configure it to do so? You'll also need to make sure that nodemon is reading the files from a docker volume mounted from the host vm under `/Users/<you>`

**Comment by codekitchen** [comment]
This will help narrow it down:

    docker run --rm -it -v $HOME/some/dir:/host ubuntu
    apt-get update && apt-get install -y inotify-tools
    inotifywait -mr /host

Then modify some files in $HOME/some/dir and see if inotifywait prints them out.

**Comment by aisipos** [comment]
Hmm, inotifywait wasn't printing anything out. I ran

```/usr/bin/fsevents_to_vm start --debug --ssh-config-file=/Users/anton/.dinghy/ssh-config```

in the foreground just to ensure that my host was forwarding events (it was). I'm unsure what to do to look at this further? What is fsevents_to_vm talking to on the container side to signal inotify, and what protocol does it go over?

Regarding `nodemon`, the most recent versions seem to use this library:
https://github.com/paulmillr/chokidar

It actually has more than one "backend", but doesn't seem to specify all of them in the readme at least. Its fallback seems to be straight polling, which is odd since in that case this should all work (my changes on the host do actually show up in the container FS).

Incidentally, I upgraded to Virtualbox 5.0.4 from 5.0.0 and installed the VirtualBox Expansion Pack (which I didn't have before), and rebuilt m VM. Same problem behavior unfortunately.

**Comment by aisipos** [comment]
Made a note of the nodemon issue in https://github.com/remy/nodemon/issues/419

**Comment by codekitchen** [comment]
> What is fsevents_to_vm talking to on the container side to signal inotify, and what protocol does it go over?

It's pretty braindead simple -- it just opens an ssh connection to the VM, and runs `touch` commands directly (https://github.com/codekitchen/fsevents_to_vm/blob/master/lib/fsevents_to_vm/ssh_emit.rb), that's why it needs the ssh-config file.

You could try running an inotify watcher like `inotifywait` directly on the VM outside of docker, but I'm not sure how you'd get that installed on the tinycore linux boot2docker distro.

**Comment by aisipos** [comment]
Since nodemon 1.7.0 restored its `-L` flag, this is working for me now. I'll note for posterity the specific issue that is the title of this ticket is fixed by not having homebrew proctools installed, specifically the proctools pgrep behaves differently.
