### ISSUE TITLE
No Port for container create

### ISSUE THREAD

**Issue by sja87** [codekitchen/dinghy#76]
Dinghy is nice but today it is a little bit curious.

When I start container with some volume from my user directory the container not start and no port ist set.

After I start it on some other directory it works! 

What happened? 

![bildschirmfoto 2015-09-22 um 14 09 08](https://cloud.githubusercontent.com/assets/4973582/10018104/47812252-6134-11e5-8d0e-b279a2f05a57.png)

**Comment by sja87** [comment]
After restart and destroy VM. Same problem :-(

**Comment by codekitchen** [comment]
Doesn't really look related to Dinghy. Your container is exiting with an error, that's what the `Exited (1)` status means. You'll need to track down what the error is, try using `docker logs` or running it in the foreground by removing the `-d` option.

**Comment by codekitchen** [comment]
I'm going to close this since it's not dinghy related
