### ISSUE TITLE
vmware provider never starts

### ISSUE THREAD

**Issue by chrisgeo** [codekitchen/dinghy#79]
Dinghy is hanging on create:

```
~ $ dinghy create --provider vmware
Creating the dinghy VM...
```

This might be a docker-machine problem but I thought I'd start here first.

**Comment by codekitchen** [comment]
Yeah that's a docker machine issue. You should be able to repro by
running docker-machine create directly.

**Comment by chrisgeo** [comment]
Looks like it is (though the virtual box provider is being a pain as well).

I'll close this out since it's unrelated. Thanks for your help!
