### ISSUE TITLE
Mount directory other than /Users

### ISSUE THREAD

**Issue by JoyceBabu** [codekitchen/dinghy#80]
Is it possible to mount a directory other than /Users using NFS? I keep all my docker data under `/opt/docker`, how can I mount the directory to the corresponding location on the VM?

**Comment by codekitchen** [comment]
partial support for this was added in https://github.com/codekitchen/dinghy/pull/45 , but it's not really complete yet. it should be usable as long as you set those env vars when you run `dinghy up`

**Comment by codekitchen** [comment]
Closing this, another PR was merged to improve on #45
