### ISSUE TITLE
Starting the dinghy VM takes very long

### ISSUE THREAD

**Issue by maxfrigge** [codekitchen/dinghy#81]
Running on a powerful machine with SSDs and what not.. it takes about 25s for `Starting the dinghy VM` and another 5-10s for the rest (including the annoying sudo password).  That's not exactly fast. Is there anything that can be done to improve this? Whats exactly happening during that time?

**Comment by codekitchen** [comment]
The `Starting the dinghy VM` step just shells out to `docker-machine start` and then writes a config file. Almost all that time is spent in spinning up the boot2docker linux VM and waiting for SSH to become available. I'm not really sure what could be done to speed that up, and it'd probably have to be changes to the docker-machine and boot2docker projects, not dinghy.

The other big delay is we sleep 5 seconds before starting the HTTP proxy, because it takes a few seconds for the docker daemon to become available even once the VM is up. I've got a TODO in the code to improve this https://github.com/codekitchen/dinghy/blob/latest/cli/cli.rb#L190 but it hasn't been a priority for me.

**Comment by maxfrigge** [comment]
Oh I understand. Thanks for your feedback.. I'll head over to the boot2docker guys and bother them :)

Is there anything I can to prevent sudo password from popping up?

I have [done this](https://docs.vagrantup.com/v2/synced-folders/nfs.html) but it did't help.

**Comment by codekitchen** [comment]
The NFS daemon dinghy uses has to run as root, so sudo will be required. You could add a NOPASSWD line to your sudoers file, I suppose.

**Comment by maxfrigge** [comment]
I have tried this from the Vagrant docs, but it didn't help. 
Are the commands dinghy uses different from those?

```
Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /usr/bin/sed -E -e /*/ d -ibak /etc/exports
%admin ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE
```

**Comment by codekitchen** [comment]
Yeah, I don't have a handy list of all the specific sudo commands so you'd have to dig through the source. There's some `sudo launchctl load` and stuff. I'm curious why you're going down this route though... do you restart dinghy often enough that typing your password is a big problem? Even as the primary developer I don't find myself restarting more than once or twice a week.

**Comment by maxfrigge** [comment]
On my laptop it's not an issue, I hardly ever restart it. But my desktop Mac get's shut down every evening - not a biggie; just thought there would be an easy way to get rid of it.

To get back to the main topic. Typing the password doesn't bother as much as waiting for the VM. But as you have already mentioned.. it's boot2docker not dinghy, so I'll just close this one.

**Comment by codekitchen** [comment]
Oh interesting. Yeah, not much I can do to speed up that step I'm afraid. Possibly `docker-machine` could be extended to allow suspending the VM, rather than shutting it down, for faster startup. I dunno if they'd be interested in supporting that though.

**Comment by gastonmorixe** [comment]
Is there any update on this specially for Mac? I'd love to suspend VM and not have to enter the password every single time.

**Comment by codekitchen** [comment]
I'm not aware of docker-machine adding suspend support, you'd have to check with that project though. If they do ever add it, it'd be easy to either call `docker-machine` directly to do the suspend/restart, or add a dinghy wrapper command.
