### ISSUE TITLE
Dinghy screwing with DNS setup?

### ISSUE THREAD

**Issue by lukebarton** [codekitchen/dinghy#83]
Since using dinghy I've had two occasions where I've had to flush my dns manually to get a site to load. It could be down to chance but since I know Dinghy is screwing with my DNS I though I'd come and ask if there is any chance it could be related.

**Comment by codekitchen** [comment]
Hm I wouldn't think so -- dinghy only controls the `.docker` TLD, by adding a config file `/etc/resolver/docker` to your host machine. This is pretty common, http://pow.cx and https://github.com/phinze/landrush both do the same thing. Shouldn't affect DNS for any other TLDs.
