### ISSUE TITLE
What will installing dinghy do to my existing docker-machine installation

### ISSUE THREAD

**Issue by shaunc** [codekitchen/dinghy#85]
This project looks interesting, but I'm wondering what it will do to my existing installation (installed via docker-toolbox 1.8.2). Also, I'm looking forward to several features in the docker 1.9 release. Will dinghy be compatible.. and what version of various docker tools does it support in any case?

I would be grateful if the documentation provide a little information about these issues. It looks a bit dangerous to "just install it". Can it exist in parallel with another installation if I want to try it out?

**Comment by codekitchen** [comment]
I haven't used the docker toolbox myself, which is why I haven't added anything to the docs about it. I've hard second-hand from others that it works fine though. Dinghy creates its own VM, it won't modify your existing one(s).

**Comment by shaunc** [comment]
Thanks! .. after Kinematic beta screwed up my old boot2docker installation I have become wary of frameworks like this. You might want to highlight *Dinghy creates its own VM, it won't modify your existing one(s).* in the docs.

**Comment by codekitchen** [comment]
good call, done
