### ISSUE TITLE
File changes can take a long time until synced

### ISSUE THREAD

**Issue by maxfrigge** [codekitchen/dinghy#86]
I am experiencing this in a node js container with gulp watching for file changes. It can take around 5-10 seconds from saving the file to gulp doing it's thing. Is there anything I can do to get this more reliable and faster?

Forgot to mention: This is happening in Virtualbox.

**Comment by maxfrigge** [comment]
I have further investigated the issue with these results.

- Sometimes it takes a few seconds and sometimes it doesn't trigger at all
- Happens in Virtualbox & VMware
- Same is happening with nodemon
- Changing the files inside the running container triggers file change immediately 

So I guess it must be somehow related to the way files are mounted into the VM. This is really killing the joys of using Docker in development environments, which is the whole point of dinghy.

**Comment by codekitchen** [comment]
does `dinghy status` show the `FSEV` service as running? That sort of delay sounds like it may not be, or that gulp/nodemon isn't configured to use inotify events (I'm not very familiar with either gulp or nodemon).

**Comment by maxfrigge** [comment]
You are right. It's nor running. Anything I can do about it?

**Comment by maxfrigge** [comment]
When I manually install and start `fsevents_to_vm`, while having dinghy running it works fine. 

```
$ gem install fsevents_to_vm
$ fsevents_to_vm start
```

Any thoughts why dinghy might not be able to start `fsevents_to_vm` itself?

**Comment by codekitchen** [comment]
Did you recently upgrade to El Capitan? I released some updates to Dinghy last week to fix issues with this on El Capitan, make sure you're on the latest: https://github.com/codekitchen/dinghy#upgrading

**Comment by maxfrigge** [comment]
Yes I am running on El Capitan. I have reinstalled the latest version and that seemed to fix it. I can't swear on it but I would say that I had already updated a few days ago.

Anyways .. my work day just go a lot happier. Thanks! :-)
