### ISSUE TITLE
move dinghy to a `brew tap`

### ISSUE THREAD

**Issue by frosenberg** [codekitchen/dinghy#91]
Have a look here: https://github.com/Homebrew/homebrew/issues/44945#issuecomment-148401038

I guess `dinghy` should use a tap as recommended by @mikemcquaid

**Comment by codekitchen** [comment]
Do you have any more info on what that means? `brew cleanup` seems to be working fine for me locally.

**Comment by mikemcquaid** [comment]
@codekitchen It'll be an old version of `dinghy` which had a syntax error. People don't receive autoupdates when they `brew install` from a URL so it's hard to debug and fix stuff like this. I strongly recommend you transition your formula to using a tap: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

**Comment by codekitchen** [comment]
Ah that makes sense thanks. I'll look into doing that at some point.

**Comment by brandontamm** [comment]
+1 for moving this to a brew tap or an official brew install would be even better :)

**Comment by adrianfalleiro** [comment]
I started working on a tap at https://github.com/adrianfalleiro/homebrew-dinghy - still needs to be tweaked a bit...

Ideally the formula should be fetching a tarball rather than doing a git checkout, but github archives don't include submodules :(

If you create a new repo `codekitchen/homebrew-dinghy` it can be tapped with `brew tap codekitchen/dingy`

**Comment by mikemcquaid** [comment]
@adrianfalleiro Nice work! I'd recommend running `brew audit --strict --online` to check your style is all :+1:. I'm happy to make suggestions if you'd like them too.

**Comment by adrianfalleiro** [comment]
Cheers @mikemcquaid, have updated the repo accordingly.

**Comment by manojlds** [comment]
Is the tap in usable state? (seems ok from reading the code, but wanted to confirm)

**Comment by codekitchen** [comment]
Thanks @adrianfalleiro ! I appreciate you picking up my slack. I've created https://github.com/codekitchen/homebrew-dinghy/blob/master/Formula/dinghy.rb based on your repo. Dinghy's `README.md` and `dev/release` script will need updating as well, I can take care of that. Migrating over from the previous install method seems to work OK.

**Comment by codekitchen** [comment]
OK, things look good. I'll try to get a couple co-workers to upgrade and verify they don't run into anything. Thanks again.
