### ISSUE TITLE
client API version: 1.20, server API version: 1.19

### ISSUE THREAD

**Issue by mlhamel** [codekitchen/dinghy#92]
Whenever I'm trying to docker build i've got this error:

`Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)`

It seems something is out of sync and dinghy up/destroy/upgrade don't seems to work

**Comment by mlhamel** [comment]
Found a couple of reference to the same kind of bug:

https://github.com/kitematic/kitematic/issues/875

Seems to be related to boot2docker but still unsure how to fix it... :(

**Comment by codekitchen** [comment]
This means your version of docker-machine is older than your version of docker. If you're using Docker Toolbox you'll have to upgrade that, but if you are just using homebrew to install them, a `brew up && brew upgrade docker-machine && dinghy upgrade` should do it.

I've been wanting to add some code to dinghy to detect version problems and suggest how to fix, but haven't gotten a chance yet.

**Comment by mlhamel** [comment]
super strange, i'm using only homebrew but by upgrading everything it doesn't work. 

what did worked althought, i've discovered in `/usr/local/var/dinghy/vagrant/VagrantFile` the box version was completely out-of-date:

```
config.vm.box_version = "1.7.1.rev1"
```

I changed it to the latest version (1.8.2) and now it work. I'm just wondering why this file was not upgraded by doing `dinghy upgrade`. Any idea ?

**Comment by codekitchen** [comment]
Oh, you are on a pretty old version of dinghy, OK. About 2 months ago dinghy switched to using docker-machine and doesn't even use Vagrant anymore, I was referring to that new setup. That makes sense then.

I'd recommend upgrading when you get a chance, I won't be releasing any versions of the Vagrant image newer than 1.8.2.

**Comment by mlhamel** [comment]
Ohhh just found https://github.com/codekitchen/dinghy/blob/latest/UPGRADE_FROM_VAGRANT.md :)

Thanks :+1:
